@extends('layouts.public')
@php
    $intro = $page?->section('intro');
    $introPayload = $intro?->payload ?? [];
    $pageTitle = $category?->name ?: ($tag ? '#'.$tag->name : ($author ? 'Notes by '.$author->name : 'News, notes & market education'));
@endphp
@section('title', $page?->seo_title ?: $pageTitle.' — Mwanafunzi Investor')
@section('description', $page?->seo_description ?: ($intro?->body ?: 'Daily updates, market education, trading reviews and practical notes from Mwanafunzi Investor.'))
@section('content')
<x-public-hero class="public-page-hero" :eyebrow="$introPayload['eyebrow'] ?? 'Journal / News & updates'" :title="$pageTitle" :summary="$intro?->body ?? 'A living record of market education, platform updates and ideas worth returning to. No invented headlines. No made-up results.'" setting="hero_journal_image" :fallback-image="config('public.hero_defaults.journal')" />
<section class="platform-section editorial-index-section"><div class="container">
    @if($featured)
        @php($featuredImage = \App\Support\PublicHero::resolve([$featured->featured_image, config('public.hero_defaults.journal')]))
        <article class="editorial-featured">
            @if($featuredImage)<a class="editorial-featured-media" href="{{ route('journal.show', $featured) }}"><img src="{{ $featuredImage['url'] }}" alt="{{ $featured->title }}" loading="eager"></a>@endif
            <div class="editorial-featured-copy"><div class="article-meta"><span>{{ $featured->category?->name ?: 'Journal' }}</span><span>{{ $featured->published_at?->format('M j, Y') }}</span></div><p class="eyebrow">Featured update</p><h2><a href="{{ route('journal.show', $featured) }}">{{ $featured->title }}</a></h2><p>{{ $featured->excerpt }}</p><div class="article-card-byline"><span>{{ $featured->displayAuthor() }}</span><span>{{ $featured->reading_time ?: 1 }} min read</span></div><a class="text-link" href="{{ route('journal.show', $featured) }}">Read the feature <span aria-hidden="true">↗</span></a></div>
        </article>
    @endif
    <form class="journal-filters editorial-filters" method="get" action="{{ route('journal') }}"><label>Search <input type="search" name="search" value="{{ $search }}" placeholder="Search title, topic or tag"></label><label>Category <select name="category"><option value="">All categories</option>@foreach($categories as $item)<option value="{{ $item->slug }}" @selected($category?->id === $item->id || request('category') === $item->slug)>{{ $item->name }}@if($item->published_articles_count) ({{ $item->published_articles_count }})@endif</option>@endforeach</select></label><button class="button button-dark" type="submit">Search journal <span aria-hidden="true">↗</span></button></form>
    @if($search !== '' || $category || $tag || $author)<div class="editorial-filter-context"><span class="eyebrow">Current view</span><strong>{{ $search !== '' ? 'Search results for “'.$search.'”' : $pageTitle }}</strong><a href="{{ route('journal') }}">Clear view <span aria-hidden="true">×</span></a></div>@endif
    @if($trending->isNotEmpty())<div class="editorial-subsection-heading"><div><p class="eyebrow">From the archive</p><h2>Worth returning to.</h2></div><a class="text-link" href="{{ route('journal') }}">All notes <span aria-hidden="true">↗</span></a></div><div class="editorial-trending-grid">@foreach($trending as $article)<article class="editorial-mini-card"><div class="article-meta"><span>{{ $article->category?->name ?: 'Journal' }}</span><span>{{ $article->likes_count + $article->comments_count }} interactions</span></div><h3><a href="{{ route('journal.show', $article) }}">{{ $article->title }}</a></h3><p>{{ \Illuminate\Support\Str::limit($article->excerpt, 120) }}</p></article>@endforeach</div>@endif
    <div class="editorial-subsection-heading"><div><p class="eyebrow">{{ $search !== '' || $category || $tag || $author ? 'Results' : 'Latest updates' }}</p><h2>{{ $search !== '' ? 'What we found.' : 'The latest notes.' }}</h2></div></div>
    <div class="article-grid editorial-article-grid">@forelse($articles as $article)@php($cardImage = \App\Support\PublicHero::resolve([$article->featured_image, config('public.hero_defaults.journal')]))<article class="article-card editorial-article-card">@if($cardImage)<a class="article-card-media" href="{{ route('journal.show', $article) }}"><img src="{{ $cardImage['url'] }}" @if($cardImage['srcset']) srcset="{{ $cardImage['srcset'] }}" sizes="(max-width: 760px) 100vw, 33vw" @endif alt="{{ $article->title }}" loading="lazy"></a>@endif<div class="article-meta"><span>{{ $article->category?->name ?: 'Journal' }}</span><span>{{ $article->published_at?->format('M j, Y') }}</span></div><h2><a href="{{ route('journal.show', $article) }}">{{ $article->title }}</a></h2><p>{{ $article->excerpt }}</p><div class="article-card-byline"><span>{{ $article->displayAuthor() }}</span><span>{{ $article->reading_time ?: 1 }} min read</span></div><div class="article-card-footer"><span>{{ $article->likes_count }} likes · {{ $article->comments_count }} comments</span><a class="text-link" href="{{ route('journal.show', $article) }}">Read <span aria-hidden="true">→</span></a></div></article>@empty<div class="empty-state editorial-empty-state"><span class="empty-index">J / 00</span><h2>{{ $search !== '' ? 'Nothing matched that search.' : 'The next entry is being studied.' }}</h2><p>{{ $search !== '' ? 'Try a broader phrase or browse the latest notes.' : ($introPayload['empty_body'] ?? 'When a new note is published, it will appear here from the connected journal source.') }}</p>@if($search !== '')<a class="button button-dark" href="{{ route('journal') }}">View latest notes <span aria-hidden="true">↗</span></a>@endif</div>@endforelse</div>
    {{ $articles->links() }}
</div></section>
@endsection
