@extends('layouts.public')
@section('title', ($article->seo_title ?: $article->title) . ' — Mwanafunzi Investor')
@section('description', $article->seo_description ?: $article->excerpt)
@section('og_type', 'article')
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Article', 'headline' => $article->title, 'description' => $article->excerpt, 'datePublished' => $article->published_at?->toIso8601String(), 'author' => ['@type' => 'Organization', 'name' => $article->author ?: 'Mwanafunzi Investor'], 'mainEntityOfPage' => route('journal.show', $article)], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<article><section class="detail-hero"><div class="container narrow"><a class="back-link" href="{{ route('journal') }}">← Journal</a><p class="eyebrow"><span class="eyebrow-line"></span> {{ $article->category?->name ?: 'Field note' }} <span class="eyebrow-dot"></span> {{ $article->published_at?->format('M j, Y') }}</p><h1>{{ $article->title }}</h1>@if($article->featured_image)<img class="detail-image" src="{{ asset('storage/'.$article->featured_image) }}" alt="{{ $article->title }}">@endif<p class="lede">{{ $article->excerpt }}</p><p class="article-byline">{{ $article->author ?: 'Mwanafunzi Investor' }} @if($article->reading_time) · {{ $article->reading_time }} min read @endif</p></div></section><section class="platform-section"><div class="container article-body"><div class="rich-copy">{!! \App\Support\RichText::render($article->content) !!}</div><aside class="detail-card"><span class="eyebrow">Keep learning</span><p>Explore the learning paths, courses and tools that give this idea somewhere to live.</p><a class="text-link" href="{{ route('learn') }}">Visit the learning hub <span aria-hidden="true">→</span></a></aside></div></section></article>
@if($relatedArticles->isNotEmpty())<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Related notes</p><div class="article-grid">@foreach($relatedArticles as $related)<article class="article-card"><h2><a href="{{ route('journal.show', $related) }}">{{ $related->title }}</a></h2><p>{{ $related->excerpt }}</p></article>@endforeach</div></div></section>@endif
@endsection
