@extends('layouts.public')
@php($ogImage = $article->og_image ? \App\Support\PublicHero::candidate($article->og_image) : \App\Support\PublicHero::resolve([$article->featured_image, config('public.hero_defaults.journal')]))
@section('title', ($article->seo_title ?: $article->title) . ' — Mwanafunzi Investor')
@section('description', $article->seo_description ?: ($article->excerpt ?: 'News, notes and market education from Mwanafunzi Investor.'))
@section('canonical', $article->canonicalUrl())
@section('robots', $article->robots ?: 'index,follow')
@section('og_title', $article->og_title ?: ($article->seo_title ?: $article->title))
@section('og_description', $article->og_description ?: ($article->seo_description ?: ($article->excerpt ?: 'News, notes and market education from Mwanafunzi Investor.')))
@section('og_type', 'article')
@if($ogImage)
@section('og_image'){{ $ogImage['url'] }}@endsection
@endif
@section('article_meta')
<meta property="article:published_time" content="{{ $article->published_at?->toIso8601String() }}">
@if($article->updated_at)
<meta property="article:modified_time" content="{{ $article->updated_at->toIso8601String() }}">
@endif
@if($article->authorMember)
<meta property="article:author" content="{{ $article->authorMember->name }}">
@endif
@endsection
@php($schemaContext = chr(64).'context')
@section('structured_data')<script type="application/ld+json">{!! json_encode([$schemaContext => 'https://schema.org', '@type' => 'BlogPosting', 'headline' => $article->title, 'description' => $article->excerpt, 'datePublished' => $article->published_at?->toIso8601String(), 'image' => $ogImage['url'] ?? null, 'author' => $article->authorMember ? ['@type' => 'Person', 'name' => $article->authorMember->name, 'url' => route('team.show', $article->authorMember)] : ['@type' => 'Organization', 'name' => 'Mwanafunzi Investor'], 'mainEntityOfPage' => $article->canonicalUrl(), 'publisher' => ['@type' => 'Organization', 'name' => 'Mwanafunzi Investor']], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<article class="editorial-article-detail"><x-public-hero class="detail-hero" compact :eyebrow="($article->category?->name ?: 'Field note').' · '.($article->published_at?->format('M j, Y') ?: 'Unscheduled')" :title="$article->title" :summary="$article->excerpt" :image="$article->featured_image" :focal-point="$article->hero_focal_point" setting="hero_journal_image" :fallback-image="config('public.hero_defaults.journal')" :metadata="array_filter([$article->displayAuthor(), $article->reading_time ? $article->reading_time.' min read' : null])" :breadcrumbs="[['label' => 'Journal', 'url' => route('journal')]]"> </x-public-hero>
<section class="platform-section"><div class="container editorial-reading-layout"><div class="editorial-reading-main"><div class="editorial-reading-toolbar"><span>{{ $article->content_type ?: 'Article' }}</span><span>{{ $article->published_at?->format('M j, Y · H:i') }}</span></div><div class="rich-copy article-body">{!! \App\Support\RichText::render($article->content) !!}</div>@if($article->tags->isNotEmpty())<div class="article-tags" aria-label="Article tags">@foreach($article->tags as $tag)<a href="{{ route('journal.tag', $tag) }}">#{{ $tag->name }}</a>@endforeach</div>@endif
@if($article->socialLinks->isNotEmpty())<section class="related-social-updates" aria-labelledby="social-updates-heading"><p class="eyebrow">Related social content</p><h2 id="social-updates-heading">Continue the update.</h2><div class="related-social-grid">@foreach($article->socialLinks as $social)<a class="related-social-card" href="{{ $social->url }}" target="_blank" rel="noopener noreferrer"><span class="related-social-icon" aria-hidden="true">↗</span><span><strong>{{ $social->label ?: 'Open this '.$social->platformLabel().' update' }}</strong><small>{{ $social->platformLabel() }}</small></span></a>@endforeach</div></section>@endif
<div class="article-disclaimer">Educational content only. This is not personalised financial advice. <a href="{{ route('legal', 'risk-disclosure') }}">Read the risk disclosure.</a></div></div><aside class="editorial-reading-aside"><div class="detail-card article-engagement-card"><p class="eyebrow">Useful note?</p>@auth<form method="post" action="{{ route('journal.reaction', $article) }}" data-reaction-form>@csrf<input type="hidden" name="type" value="like"><button class="article-like-button {{ $userHasLiked ? 'is-active' : '' }}" type="submit" aria-pressed="{{ $userHasLiked ? 'true' : 'false' }}"><span aria-hidden="true">{{ $userHasLiked ? '♥' : '♡' }}</span> <span data-reaction-count>{{ $article->likes_count }}</span> <span>Like</span></button></form>@else<a class="article-like-button" href="{{ route('login') }}">♡ {{ $article->likes_count }} <span>Sign in to like</span></a>@endauth<div class="article-share" data-share-url="{{ $article->canonicalUrl() }}"><span class="eyebrow">Share</span><div class="article-share-links"><button type="button" data-copy-link>Copy link</button><a href="https://wa.me/?text={{ urlencode($article->title.' '.$article->canonicalUrl()) }}" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="https://www.linkedin.com/sharing/share-offsite/?url={{ urlencode($article->canonicalUrl()) }}" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://twitter.com/intent/tweet?text={{ urlencode($article->title) }}&url={{ urlencode($article->canonicalUrl()) }}" target="_blank" rel="noopener noreferrer">X</a></div><span class="share-feedback" data-share-feedback role="status" aria-live="polite"></span></div></div>@if($article->authorMember)<div class="detail-card article-author-card">@if($article->authorMember->portrait)<img src="{{ \App\Support\PublicHero::candidate($article->authorMember->portrait)['url'] ?? asset('storage/'.$article->authorMember->portrait) }}" alt="{{ $article->authorMember->name }}" loading="lazy">@endif<p class="eyebrow">Written by</p><h2>{{ $article->authorMember->name }}</h2><p>{{ $article->authorMember->role }}</p><a class="text-link" href="{{ route('team.show', $article->authorMember) }}">View profile <span aria-hidden="true">↗</span></a></div>@endif</aside></div></section></article>
<section class="platform-section platform-muted editorial-comments" id="comments"><div class="container editorial-comments-inner"><div class="editorial-subsection-heading"><div><p class="eyebrow">Discussion</p><h2>Join the discussion.</h2></div><span>{{ $article->comments_count }} approved comments</span></div>@if(!empty($preview))<div class="comment-signin"><p>Discussion is disabled in a private preview.</p></div>@elseif(auth()->check())<div class="comment-form-card"><form method="post" action="{{ route('journal.comments.store', $article) }}">@csrf<label for="comment-body">Comment</label><textarea id="comment-body" name="body" rows="4" required maxlength="3000" placeholder="Share a considered response."></textarea><input class="comment-honeypot" type="text" name="website" tabindex="-1" autocomplete="off"><button class="button button-dark" type="submit">Post comment <span aria-hidden="true">↗</span></button></form></div>@else<div class="comment-signin"><p>Sign in to add a comment or reply.</p><a class="button button-dark" href="{{ route('login') }}">Sign in to comment <span aria-hidden="true">↗</span></a></div>@endif<div class="comment-list">@forelse($comments as $comment)<div class="comment-thread"><article class="comment-item"><span class="comment-avatar" aria-hidden="true">{{ $comment->initials() }}</span><div class="comment-copy"><div class="comment-meta"><strong>{{ $comment->displayName() }}</strong><time datetime="{{ $comment->created_at->toIso8601String() }}">{{ $comment->created_at->format('M j, Y') }}</time>@if($comment->edited_at)<span>Edited</span>@endif</div><p>{{ $comment->body }}</p>@if(empty($preview) && auth()->check())<details class="comment-reply"><summary>Reply</summary><form method="post" action="{{ route('journal.comments.store', $article) }}">@csrf<input type="hidden" name="parent_id" value="{{ $comment->id }}"><textarea name="body" rows="3" required maxlength="3000" placeholder="Write a reply."></textarea><button class="button button-secondary button-small" type="submit">Post reply</button></form></details>@endif</div></article>@if($comment->replies->isNotEmpty())<div class="comment-replies">@foreach($comment->replies as $reply)<article class="comment-item"><span class="comment-avatar" aria-hidden="true">{{ $reply->initials() }}</span><div class="comment-copy"><div class="comment-meta"><strong>{{ $reply->displayName() }}</strong><time datetime="{{ $reply->created_at->toIso8601String() }}">{{ $reply->created_at->format('M j, Y') }}</time></div><p>{{ $reply->body }}</p></div></article>@endforeach</div>@endif</div>@empty<div class="comment-empty">No comments yet. Start a useful conversation.</div>@endforelse</div></div></section>
@if($relatedArticles->isNotEmpty())<section class="platform-section"><div class="container"><div class="editorial-subsection-heading"><div><p class="eyebrow">Keep reading</p><h2>Related notes.</h2></div></div><div class="article-grid">@foreach($relatedArticles as $related)<article class="article-card"><div class="article-meta"><span>{{ $related->category?->name ?: 'Journal' }}</span><span>{{ $related->published_at?->format('M j, Y') }}</span></div><h2><a href="{{ route('journal.show', $related) }}">{{ $related->title }}</a></h2><p>{{ $related->excerpt }}</p><a class="text-link" href="{{ route('journal.show', $related) }}">Read note <span aria-hidden="true">→</span></a></article>@endforeach</div></div></section>@endif
@endsection
