<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mwanafunzi Investor is a financial education brand for systematic trading, probability, risk management and disciplined portfolio thinking.">
    <meta name="theme-color" content="#171817">
    <meta property="og:title" content="Mwanafunzi Investor — Become a Student of Money">
    <meta property="og:description" content="Systematic trading. Probability. Risk. Discipline. Learn markets without the hype.">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="en_TZ">
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
    <title>Mwanafunzi Investor — Become a Student of Money</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <a class="skip-link" href="#main-content">Skip to content</a>
    <header class="site-header" data-header>
        <div class="header-inner container">
            <a class="brand" href="#top" aria-label="Mwanafunzi Investor home"><span class="brand-mark" aria-hidden="true"><span></span><span></span><span></span></span><span class="brand-copy"><strong>MWANAFUNZI</strong><small>INVESTOR</small></span></a>
            <nav class="desktop-nav" aria-label="Primary navigation"><a class="active" href="#top">Home</a><a href="#philosophy">Learn</a><a href="#courses">Courses</a><a href="#tools">Tools</a><a href="#journal">Journal</a><a href="#about">About</a></nav>
            <div class="header-actions"><a class="header-contact" href="mailto:mwanafunziinvestor@outlook.com">Contact</a><a class="button button-small button-light" href="#contact">Student Portal <span aria-hidden="true">↗</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" data-menu-toggle><span class="sr-only">Open menu</span><span></span><span></span></button></div>
        </div>
        <div class="mobile-menu" id="mobile-menu" data-mobile-menu><nav aria-label="Mobile navigation"><a href="#top">Home <span>01</span></a><a href="#philosophy">Learn <span>02</span></a><a href="#courses">Courses <span>03</span></a><a href="#tools">Tools <span>04</span></a><a href="#journal">Journal <span>05</span></a><a href="#about">About <span>06</span></a></nav><a class="button button-dark" href="#contact">Contact the desk <span aria-hidden="true">↗</span></a></div>
    </header>
    <main id="main-content">
        <section class="hero" id="top"><div class="hero-image" role="img" aria-label="A student of money reviewing market research at a desk"></div><div class="hero-overlay"></div><div class="hero-grid container"><div class="hero-content reveal"><p class="eyebrow eyebrow-light"><span class="eyebrow-line"></span> Financial education for the long game</p><h1>Become a<br><em>Student of Money.</em></h1><p class="hero-lede">Systematic Trading. Probability. Risk. Discipline.<br>Learn to understand markets, develop mechanical trading rules and protect your capital without the hype.</p><div class="hero-buttons"><a class="button button-accent" href="#courses">Start Learning <span aria-hidden="true">↗</span></a><a class="text-link text-link-light" href="#tools">Explore Trading Tools <span aria-hidden="true">→</span></a></div><p class="hero-note">Forex Education <i></i> Risk Management <i></i> Trading Systems <i></i> Portfolio Thinking</p></div><div class="hero-aside reveal reveal-delay-2"><div class="hero-aside-rule"></div><p>For the person who wants<br>to understand, not predict.</p><span>01 / 04</span></div></div><a class="scroll-cue" href="#philosophy"><span>Scroll to explore</span><i aria-hidden="true">↓</i></a></section>

        <section class="section philosophy" id="philosophy"><div class="container philosophy-grid"><div class="section-intro reveal"><p class="eyebrow"><span class="eyebrow-line"></span> A different kind of market education</p><h2>Trading is not prediction.<br><em>It is decision-making</em><br>under uncertainty.</h2><p class="body-copy">The market does not owe us certainty. Mwanafunzi Investor exists to help you build a process that can hold up when certainty is impossible — through probability, rules and responsible risk.</p><a class="text-link" href="#framework">Discover the framework <span aria-hidden="true">→</span></a></div><div class="philosophy-visual reveal reveal-delay-1"><div class="photo-card photo-card-back" aria-hidden="true"></div><div class="photo-card photo-card-main"><div class="desk-scene"><span class="desk-sun"></span><span class="desk-paper paper-one"></span><span class="desk-paper paper-two"></span><span class="desk-pencil"></span></div><div class="visual-caption"><span>Study the process</span><strong>01</strong></div></div><div class="circle-note"><span>Always a<br><em>mwanafunzi.</em></span><i>↗</i></div></div></div><div class="container pillars reveal"><div class="pillar"><span>01</span><strong>Student of Money</strong><p>Stay curious. Study the relationships behind the price.</p></div><div class="pillar"><span>02</span><strong>Systems over signals</strong><p>Turn ideas into rules you can test, repeat and review.</p></div><div class="pillar"><span>03</span><strong>Probability + discipline</strong><p>Respect the sample size, the risk and the work.</p></div></div></section>

        <section class="section services-section" id="learn"><div class="container"><div class="section-heading split-heading reveal"><div><p class="eyebrow"><span class="eyebrow-line"></span> Start with a stronger foundation</p><h2>Build the habits<br>behind the <em>chart.</em></h2></div><p class="body-copy">Four practical entry points for replacing noise with a calm, structured way of thinking about markets.</p></div><div class="service-grid">@php $services = [['01', '◒', 'Forex Core Basics — No BS', 'Understand the language of the market, from currency pairs to the forces that move them.'], ['02', '⌁', 'Mechanical Analysis Concepts, Rules & Execution', 'Learn how to translate an idea into a repeatable, testable decision process.'], ['03', '◌', 'Risk Planning', 'Make position size, exposure and the cost of being wrong part of the plan.'], ['04', '↗', 'Running Trade Risk Management', 'Manage an open position with rules that protect your thinking as conditions change.']]; @endphp @foreach ($services as $service)<a class="service-card reveal" href="#contact"><div class="card-top"><span class="card-number">{{ $service[0] }}</span><span class="card-icon" aria-hidden="true">{{ $service[1] }}</span></div><h3>{{ $service[2] }}</h3><p>{{ $service[3] }}</p><span class="card-link">Learn more <span aria-hidden="true">↗</span></span></a>@endforeach</div></div></section>

        <section class="framework-section" id="framework"><div class="container"><div class="framework-header reveal"><p class="eyebrow eyebrow-light"><span class="eyebrow-line"></span> A process you can come back to</p><h2>The Student of Money<br><em>Framework.</em></h2><p>Good decisions become easier when they have somewhere to live.</p></div><div class="framework-steps">@php $steps = [['01', 'Learn', 'Understand the market and your own assumptions.'], ['02', 'Define Rules', 'Write down what must be true before you act.'], ['03', 'Plan Risk', 'Decide what you can responsibly put at risk.'], ['04', 'Execute', 'Follow the plan without negotiating with fear.'], ['05', 'Journal', 'Capture the decision while the context is clear.'], ['06', 'Review', 'Look for patterns across a meaningful sample.'], ['07', 'Improve', 'Make one thoughtful change at a time.']]; @endphp @foreach ($steps as $step)<div class="framework-step reveal"><span>{{ $step[0] }}</span><strong>{{ $step[1] }}</strong><p>{{ $step[2] }}</p></div>@endforeach</div></div></section>

        <section class="section products-section" id="tools"><div class="container"><div class="section-heading split-heading reveal"><div><p class="eyebrow"><span class="eyebrow-line"></span> Tools for deliberate practice</p><h2>Make the process<br><em>visible.</em></h2></div><p class="body-copy">Simple, focused tools for turning a good intention into a record you can learn from. Product availability and pricing can be configured as the catalogue grows.</p></div><div class="product-grid">
            <article class="product-card product-featured reveal"><div class="product-mockup journal-mockup"><div class="mockup-top"><span>TRADING JOURNAL</span><span>2024 — 25</span></div><div class="journal-line large"></div><div class="journal-line medium"></div><div class="journal-columns"><span></span><span></span><span></span></div><div class="journal-grid-lines"></div><div class="mockup-stamp">REVIEW<br>THE<br>PROCESS</div></div><div class="product-copy"><span class="product-category">Template / Notion or Sheet</span><h3>Trading Journal Sheet</h3><p>A calm place to capture the plan, execution and lesson behind each decision.</p><div class="product-meta"><span>View tool <b>↗</b></span><span>Price on request</span></div></div></article>
            <article class="product-card reveal reveal-delay-1"><div class="product-mockup simulator-mockup"><div class="mockup-top"><span>MT SIMULATOR</span><span>01</span></div><div class="sim-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="sim-controls"><span></span><span></span><span></span></div></div><div class="product-copy"><span class="product-category">Practice / Simulation</span><h3>MT Simulator</h3><p>Rehearse your rules in a controlled environment before the pressure is real.</p><div class="product-meta"><span>Learn more <b>↗</b></span><span>Coming soon</span></div></div></article>
            <article class="product-card reveal reveal-delay-2"><div class="product-mockup risk-mockup"><div class="mockup-top"><span>RISK PLANNER</span><span>R:R</span></div><div class="risk-ring"><span>PLAN<br><b>FIRST</b></span></div><div class="risk-values"><span>Risk / trade <b>—</b></span><span>Exposure <b>—</b></span><span>Drawdown <b>—</b></span></div></div><div class="product-copy"><span class="product-category">Planning / Spreadsheet</span><h3>Risk Planner / Manager</h3><p>Bring risk per trade, portfolio exposure and the bigger picture into one view.</p><div class="product-meta"><span>Get product <b>↗</b></span><span>Price on request</span></div></div></article>
            <article class="product-card product-wide reveal"><div class="product-mockup calculator-mockup"><div class="mockup-top"><span>MT RISK CALCULATOR</span><span>INPUT / OUTPUT</span></div><div class="calc-row"><span>Account size</span><b>— — —</b></div><div class="calc-row"><span>Risk percentage</span><b>— — —</b></div><div class="calc-result"><span>Position size</span><strong>Set by your plan</strong></div></div><div class="product-copy"><span class="product-category">Utility / Calculator</span><h3>MT Risk Calculator</h3><p>Keep position sizing mechanical, clear and accountable before you place a trade.</p><div class="product-meta"><span>View tool <b>↗</b></span><span>Coming soon</span></div></div></article>
        </div></div></section>

        <section class="section probability-section" id="about"><div class="container probability-grid"><div class="probability-copy reveal"><p class="eyebrow"><span class="eyebrow-line"></span> The mathematics of staying in the game</p><h2>You don't need to be right on <em>every trade.</em></h2><p class="body-copy">You need controlled losses, repeatable execution and an edge that can express itself across a meaningful sample of trades.</p><a class="button button-dark" href="#contact">Learn risk management <span aria-hidden="true">↗</span></a></div><div class="dashboard-card reveal reveal-delay-1"><div class="dashboard-header"><span>PROCESS DASHBOARD</span><span class="dashboard-status"><i></i> No results fabricated</span></div><div class="dashboard-body"><div class="dashboard-graph"><div class="graph-labels"><span>EDGE</span><span>TIME →</span></div><svg viewBox="0 0 520 220" role="img" aria-label="Abstract process line showing variation over time"><path d="M0 171 C40 169 50 110 83 123 S124 163 154 123 S195 81 224 118 S265 177 294 136 S330 82 362 104 S395 131 421 83 S472 79 520 34" fill="none" stroke="currentColor" stroke-width="2"/><path d="M0 181 C40 179 50 154 83 164 S124 180 154 156 S195 134 224 151 S265 185 294 162 S330 145 362 147 S395 162 421 128 S472 121 520 89" fill="none" stroke="currentColor" stroke-opacity=".25" stroke-width="1" stroke-dasharray="4 5"/></svg></div><div class="dashboard-metrics"><div><span>Risk per trade</span><strong>Defined</strong></div><div><span>Expected R</span><strong>Tested</strong></div><div><span>Sample size</span><strong>Respected</strong></div><div><span>Execution quality</span><strong>Reviewed</strong></div></div></div></div></div></section>

        <section class="discipline-section"><div class="container discipline-grid"><div class="discipline-mark reveal" aria-hidden="true">✦</div><div class="discipline-copy reveal reveal-delay-1"><p class="eyebrow eyebrow-light"><span class="eyebrow-line"></span> The work beyond the chart</p><h2>Discipline <em>Beyond</em><br>The Charts.</h2><p>Patience. Stewardship. Self-control. Humility. Consistency. Responsibility.</p><p class="discipline-small">Financial education is also an education in how we carry uncertainty. The point is not perfection — it is becoming trustworthy with the decisions in front of you.</p></div></div></section>

        <section class="section journal-section" id="journal"><div class="container"><div class="section-heading split-heading reveal"><div><p class="eyebrow"><span class="eyebrow-line"></span> Field notes, when there are field notes</p><h2>Real Updates.<br><em>Real Journey.</em></h2></div><p class="body-copy">The journal will be a living record of the work: reviews, lessons and ideas worth returning to. No invented headlines. No made-up results.</p></div><div class="journal-empty reveal"><div class="empty-index">J / 00</div><div><h3>The next entry is being studied.</h3><p>When a new note is published, it will appear here from the connected journal source.</p></div><a class="text-link" href="mailto:mwanafunziinvestor@outlook.com?subject=Journal%20updates">Ask for updates <span aria-hidden="true">↗</span></a></div></div></section>

        <section class="section courses-section" id="courses"><div class="container"><div class="section-heading split-heading reveal"><div><p class="eyebrow"><span class="eyebrow-line"></span> Learn in the right order</p><h2>Courses for the<br><em>long game.</em></h2></div><p class="body-copy">Practical education for people who are ready to build a process — without profitability guarantees or shortcuts.</p></div><div class="course-list">@php $courses = [['01', 'Forex Foundations', 'Start with market structure, language, context and the habits of a careful student.', 'Foundation', 'Self-paced'], ['02', 'Building a Mechanical Trading System', 'Move from a market idea to clear rules you can test and repeat.', 'Intermediate', 'Self-paced'], ['03', 'Risk Planning & Capital Preservation', 'Learn how to keep risk visible before a trade, a week or a portfolio.', 'All levels', 'Guided'], ['04', 'Running Trade Management', 'Practice the decisions that matter after an entry: manage, document and review.', 'Intermediate', 'Coming soon']]; @endphp @foreach ($courses as $course)<a class="course-row reveal" href="#contact"><span class="course-number">{{ $course[0] }}</span><div class="course-name"><h3>{{ $course[1] }}</h3><p>{{ $course[2] }}</p></div><div class="course-detail"><span>{{ $course[3] }}</span><span>{{ $course[4] }}</span></div><span class="course-arrow" aria-hidden="true">↗</span></a>@endforeach</div></div></section>

        <section class="final-cta" id="contact"><div class="container final-cta-inner reveal"><p class="eyebrow eyebrow-light"><span class="eyebrow-line"></span> Come back to the process</p><h2>Markets will always be uncertain.<br><em>Your process doesn't have to be.</em></h2><p>Become a Student of Money.</p><div class="hero-buttons"><a class="button button-accent" href="mailto:mwanafunziinvestor@outlook.com?subject=Start%20Learning">Start Learning <span aria-hidden="true">↗</span></a><a class="text-link text-link-light" href="#tools">Explore Tools <span aria-hidden="true">→</span></a></div></div></section>
    </main>
    <footer class="site-footer"><div class="container"><div class="footer-top"><div class="footer-brand"><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true"><span></span><span></span><span></span></span><span class="brand-copy"><strong>MWANAFUNZI</strong><small>INVESTOR</small></span></a><p>Student of Money.<br>Probability. Systems. Discipline.</p></div><div class="footer-nav"><div><span>Explore</span><a href="#philosophy">Learn</a><a href="#courses">Courses</a><a href="#tools">Tools</a></div><div><span>Company</span><a href="#journal">Journal</a><a href="#about">About</a><a href="#contact">Contact</a></div><div class="footer-contact"><span>Contact</span><a href="mailto:mwanafunziinvestor@outlook.com">mwanafunziinvestor@outlook.com</a><a href="tel:+255787172686">+255 787 172 686</a><p>Tanzania</p></div></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Mwanafunzi Investor</span><div><a href="#top">Privacy</a><a href="#top">Terms</a></div><strong>ALWAYS A MWANAFUNZI.</strong></div></div></footer>
    <div class="toast" role="status" aria-live="polite" data-toast></div>
</body>
</html>
