@extends('layouts.admin')
@section('title', $project->exists ? 'Edit case study' : 'Add case study')
@section('portal-heading', 'Projects')
@section('content')
<x-admin.page-header eyebrow="Portfolio / Case studies" title="{{ $project->exists ? 'Edit case study' : 'Add case study' }}" description="Use structured fields so the public case study can stay concise, factual and easy to scan." />
<form class="admin-form admin-editor-form" method="post" action="{{ $action }}">@csrf @if($project->exists) @method('put') @endif
<x-admin.form-section title="Project identity"><div class="form-row"><label>Title<input name="title" value="{{ old('title', $project->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $project->slug) }}" required></label></div><div class="form-row"><label>Client name <span>(optional)</span><input name="client_name" value="{{ old('client_name', $project->client_name) }}"></label><label>Industry<input name="industry" value="{{ old('industry', $project->industry) }}"></label></div><div class="form-row"><label>Project type<input name="project_type" value="{{ old('project_type', $project->project_type) }}"></label><label>Platform<input name="platform" value="{{ old('platform', $project->platform) }}"></label></div><label>Short description<textarea name="short_description" rows="3" required>{{ old('short_description', $project->short_description) }}</textarea></label></x-admin.form-section>
<x-admin.form-section title="Hero and overview"><x-admin.media-field name="featured_image" label="Featured image" :value="$project->featured_image" :media="$media" /><label>Full introduction<textarea name="full_introduction" rows="7">{{ old('full_introduction', $project->full_introduction) }}</textarea></label><div class="form-row"><label>Timeline<input name="timeline" value="{{ old('timeline', $project->timeline) }}"></label><label>Project date<input type="date" name="project_date" value="{{ old('project_date', $project->project_date?->format('Y-m-d')) }}"></label></div></x-admin.form-section>
<x-admin.form-section title="Case study content"><label>Challenge<textarea name="challenge" rows="6">{{ old('challenge', $project->challenge) }}</textarea></label><label>My role<textarea name="role" rows="6">{{ old('role', $project->role) }}</textarea></label><label>Approach<textarea name="approach" rows="6">{{ old('approach', $project->approach) }}</textarea></label><label>Solution<textarea name="solution" rows="6">{{ old('solution', $project->solution) }}</textarea></label><p class="field-help">These fields support controlled rich text. Do not add claims that cannot be supported by the project record.</p></x-admin.form-section>
<x-admin.form-section title="Features, technology and results"><label>Technologies <span>(one per line)</span><textarea name="technologies" rows="4">{{ old('technologies', collect($project->technologies ?: [])->implode("\n")) }}</textarea></label><label>Key features <span>(one per line: title | description)</span><textarea name="features" rows="6">{{ old('features', collect($project->features ?: [])->map(fn($item) => ($item['title'] ?? '').' | '.($item['description'] ?? ''))->implode("\n")) }}</textarea></label><label>Results / impact <span>(one per line: label | value | description)</span><textarea name="results" rows="6">{{ old('results', collect($project->results ?: [])->map(fn($item) => ($item['label'] ?? '').' | '.($item['value'] ?? '').' | '.($item['description'] ?? ''))->implode("\n")) }}</textarea></label></x-admin.form-section>
<x-admin.form-section title="Services and gallery"><fieldset class="form-section"><legend>Related services</legend><div class="admin-check-grid">@foreach($services as $service)<label class="admin-check"><input type="checkbox" name="service_ids[]" value="{{ $service->id }}" @checked(in_array($service->id, old('service_ids', $project->services->pluck('id')->all()), true))><span>{{ $service->title }}</span></label>@endforeach</div></fieldset><fieldset class="form-section"><legend>Project gallery</legend><p class="field-help">Select existing media assets. Add alt text and captions for each screenshot.</p>@php($galleryItems = $project->exists ? $project->gallery->keyBy('id') : collect()) @for($i = 0; $i < max(4, $galleryItems->count()); $i++) @php($galleryItem = $galleryItems->values()->get($i))<div class="project-gallery-editor"><label>Image<select name="gallery[{{ $i }}][media_id]"><option value="">No image</option>@foreach($media as $item)<option value="{{ $item->id }}" @selected((int) old("gallery.$i.media_id", $galleryItem?->id) === $item->id)>{{ $item->filename }}{{ $item->width ? ' · '.$item->width.'×'.$item->height : '' }}</option>@endforeach</select></label><label>Alt text<input name="gallery[{{ $i }}][alt_text]" value="{{ old("gallery.$i.alt_text", $galleryItem?->pivot?->alt_text ?: $galleryItem?->alt_text) }}"></label><label>Caption<input name="gallery[{{ $i }}][caption]" value="{{ old("gallery.$i.caption", $galleryItem?->pivot?->caption) }}"></label><input type="hidden" name="gallery[{{ $i }}][sort_order]" value="{{ $i }}"></div>@endfor</fieldset></x-admin.form-section>
<x-admin.form-section title="Publishing and links"><div class="form-row"><label>Status<select name="status"><option value="draft" @selected(old('status', $project->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $project->status) === 'published')>Published</option><option value="archived" @selected(old('status', $project->status) === 'archived')>Archived</option></select></label><label>Published at<input type="datetime-local" name="published_at" value="{{ old('published_at', $project->published_at?->format('Y-m-d\TH:i')) }}"></label></div><div class="form-row"><label>Display order<input type="number" name="display_order" min="0" value="{{ old('display_order', $project->display_order) }}" required></label><x-admin.toggle name="is_featured" label="Featured on public surfaces" :checked="old('is_featured', $project->is_featured) == true" /></div><div class="form-row"><label>Live URL<input type="url" name="live_url" value="{{ old('live_url', $project->live_url) }}"></label><label>Repository URL <span>(if public)</span><input type="url" name="repository_url" value="{{ old('repository_url', $project->repository_url) }}"></label></div></x-admin.form-section>
<x-admin.form-section title="SEO"><div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $project->seo_title) }}"></label><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $project->canonical_url) }}"></label></div><label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $project->seo_description) }}</textarea></label><div class="form-row"><label>Robots<select name="robots"><option value="index,follow" @selected(old('robots', $project->robots ?: 'index,follow') === 'index,follow')>Index, follow</option><option value="noindex,nofollow" @selected(old('robots', $project->robots) === 'noindex,nofollow')>No index</option></select></label><x-admin.media-field name="og_image" label="Open Graph image" :value="$project->og_image" :media="$media" /></div></x-admin.form-section>
<div class="admin-form-actions"><button class="button button-primary" type="submit">Save case study <span aria-hidden="true">↗</span></button><a class="button button-secondary" href="{{ route('admin.projects') }}">Cancel</a></div>
</form>
@endsection
