<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="font-family" content="DM Sans">
<title>Page not found — Mwanafunzi Investor</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
<style>
:root{--ink:#171817;--copper:#c56c38}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--ink);color:#fff;font:16px/1.6 'DM Sans',Arial,sans-serif}.error-page{position:relative;display:grid;min-height:100vh;align-items:center;overflow:hidden;padding:50px 7vw}.error-page::before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(16,17,16,.94),rgba(16,17,16,.68) 54%,rgba(16,17,16,.3)),url('{{ asset('images/hero-legal.webp') }}') center/cover no-repeat}.error-content{position:relative;z-index:1;max-width:680px}.eyebrow{color:var(--copper);font:600 11px 'DM Sans',Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase}.eyebrow-line{display:inline-block;width:36px;height:1px;margin:0 12px 3px 0;background:currentColor}h1{max-width:620px;margin:25px 0 20px;font:500 clamp(48px,8vw,90px)/.95 Georgia,serif;letter-spacing:-.06em}p{max-width:520px;color:rgba(255,255,255,.68)}.button{display:inline-flex;margin-top:12px;padding:13px 18px;background:var(--copper);color:#fff;text-decoration:none;font-weight:600}.button:focus-visible{outline:2px solid #fff;outline-offset:4px}@media(max-width:600px){.error-page{padding:32px 20px}.error-page::before{background:linear-gradient(0deg,rgba(16,17,16,.96),rgba(16,17,16,.52)),url('{{ asset('images/hero-legal.webp') }}') center/cover no-repeat}}
</style>
</head>
<body><main class="error-page"><div class="error-content"><p class="eyebrow"><span class="eyebrow-line"></span>404 / Keep studying</p><h1>This page is still being mapped.</h1><p>The route you requested does not exist. Come back to the process and continue from the learning hub.</p><a class="button" href="{{ route('home') }}">Return home ↗</a></div></main></body>
</html>
