@extends('layouts.public')
@php
    $intro = $page?->section('intro');
    $introPayload = $intro?->payload ?? [];
@endphp
@section('title', $page?->seo_title ?: 'Courses — Mwanafunzi Investor')
@section('description', $page?->seo_description ?: ($intro?->body ?: 'Practical financial education courses for market structure, systematic trading and risk-first decision-making.'))
@section('content')
<x-public-hero class="public-page-hero" :eyebrow="$introPayload['eyebrow'] ?? 'Learn in the right order'" :title="$intro?->heading ?? 'Courses for the long game.'" :summary="$intro?->body ?? 'Practical education for people who are ready to build a process — without profitability guarantees or shortcuts.'" setting="hero_courses_image" :fallback-image="config('public.hero_defaults.courses')" />
<section class="platform-section"><div class="container"><div class="course-list platform-course-list">@forelse($courses as $course)@php($cardImage = \App\Support\PublicHero::resolve([$course->featured_image, config('public.hero_defaults.courses')]))<a class="course-row" href="{{ route('courses.show', $course) }}"><span class="course-number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div class="course-name">@if($cardImage)<div class="course-row-media"><img src="{{ $cardImage['url'] }}" @if($cardImage['srcset']) srcset="{{ $cardImage['srcset'] }}" sizes="(max-width: 760px) 100vw, 40vw" @endif alt="" loading="lazy"></div>@endif<h2>{{ $course->title }}</h2><p>{{ $course->short_description }}</p></div><div class="course-detail"><span>{{ $course->level }}</span><span>{{ str_replace('_', ' ', $course->status) }}</span></div><span class="course-arrow" aria-hidden="true">↗</span></a>@empty<div class="empty-state"><span class="empty-index">{{ $introPayload['empty_index'] ?? 'COURSES' }}</span><h2>{{ $introPayload['empty_heading'] ?? 'The first course is being prepared.' }}</h2><p>{{ $introPayload['empty_body'] ?? 'Join the conversation to hear when enrolment opens.' }}</p>@if(!empty($introPayload['empty_cta_label']) && !empty($introPayload['empty_cta_url']) && \Illuminate\Support\Str::startsWith($introPayload['empty_cta_url'], ['/','http://','https://']))<a class="button button-dark" href="{{ $introPayload['empty_cta_url'] }}">{{ $introPayload['empty_cta_label'] }} <span aria-hidden="true">↗</span></a>@endif</div>@endforelse</div>{{ $courses->links() }}</div></section>
@endsection
