@extends('layouts.public')
@php($ogImage = $course->og_image ? \App\Support\PublicHero::candidate($course->og_image) : null)
@section('title', ($course->seo_title ?: $course->title) . ' — Mwanafunzi Investor')
@section('description', $course->seo_description ?: $course->short_description)
@section('canonical', $course->canonical_url ?: route('courses.show', $course))
@section('robots', $course->robots ?: 'index,follow')
@section('og_title', $course->og_title ?: ($course->seo_title ?: $course->title))
@section('og_description', $course->og_description ?: ($course->seo_description ?: $course->short_description))
@if($ogImage) @section('og_image', $ogImage['url']) @endif
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Course', 'name' => $course->title, 'description' => $course->short_description, 'url' => route('courses.show', $course), 'image' => $ogImage['url'] ?? null, 'provider' => ['@type' => 'Organization', 'name' => \App\Models\SiteSetting::getValue('brand_name', 'Mwanafunzi Investor')]], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<x-public-hero class="detail-hero" compact :eyebrow="trim(($course->level ?: 'Course').' · '.($course->duration ?: 'Self-paced'))" :title="$course->title" :summary="$course->short_description" :image="$course->featured_image" :focal-point="$course->hero_focal_point" setting="hero_courses_image" :fallback-image="config('public.hero_defaults.courses')" :metadata="[$course->status]" :breadcrumbs="[['label' => 'All courses', 'url' => route('courses')]]"><div class="detail-actions"><span class="status-badge">{{ str_replace('_', ' ', $course->status) }}</span>@if($course->status === 'coming_soon')<a class="button button-accent" href="#waitlist">Join the waitlist <span aria-hidden="true">↗</span></a>@elseif($course->isPublishedForPurchase() && $course->enrollment_available)<a class="button button-accent" href="{{ auth()->check() && auth()->user()->hasVerifiedEmail() ? route('checkout.course', $course) : route('login') }}">{{ $course->price && $course->price !== '0.00' ? 'Enroll securely' : 'Enroll for free' }} <span aria-hidden="true">↗</span></a>@else<a class="button button-light" href="{{ route('contact') }}">{{ $course->cta_label ?: 'Ask about this course' }} <span aria-hidden="true">↗</span></a>@endif</div></x-public-hero>
<section class="platform-section"><div class="container two-column detail-grid"><div><p class="eyebrow">About the course</p><div class="rich-copy">{!! \App\Support\RichText::render($course->full_description ?: $course->short_description) !!}</div>@if($course->learning_outcomes)<h2>What you will practise</h2><ul class="check-list">@foreach($course->learning_outcomes as $outcome)<li>{{ $outcome }}</li>@endforeach</ul>@endif</div><aside class="detail-card"><span class="eyebrow">Course notes</span><dl><div><dt>Level</dt><dd>{{ $course->level ?: 'To be confirmed' }}</dd></div><div><dt>Format</dt><dd>{{ $course->duration ?: 'To be confirmed' }}</dd></div><div><dt>Availability</dt><dd>{{ str_replace('_', ' ', $course->status) }}</dd></div></dl><p>No profitability guarantees. This is financial education, not personalised advice.</p></aside></div></section>
<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Curriculum</p><h2>What is covered</h2><div class="module-list">@forelse($course->modules as $module)<details><summary>{{ $module->title }} <span>+</span></summary><p>{{ $module->description }}</p>@foreach($module->lessons as $lesson)<div class="lesson-row">{{ $lesson->title }}</div>@endforeach</details>@empty<div class="empty-state compact"><h3>Curriculum is being prepared.</h3><p>We will publish the modules when they are ready to support a careful learning experience.</p></div>@endforelse</div></div></section>
@if($course->faqs->isNotEmpty())<section class="platform-section"><div class="container"><p class="eyebrow">Questions</p><h2>Course FAQs</h2><div class="module-list">@foreach($course->faqs as $faq)<details><summary>{{ $faq->question }} <span>+</span></summary><p>{{ $faq->answer }}</p></details>@endforeach</div></div></section>@endif
@if($course->status === 'coming_soon')<section class="platform-section platform-muted" id="waitlist"><div class="container narrow"><p class="eyebrow">Course waitlist</p><h2>Be notified when this course is ready.</h2><form class="admin-form account-form" method="post" action="{{ route('courses.waitlist', $course) }}">@csrf @include('partials.form-feedback')<label>Name<input name="name" value="{{ old('name', auth()->user()?->name) }}" required></label><label>Email<input type="email" name="email" value="{{ old('email', auth()->user()?->email) }}" required></label><label class="consent"><input type="checkbox" name="consent" value="1" required> <span>I agree to receive updates about this course only.</span></label><button class="button button-dark" type="submit">Join waitlist <span aria-hidden="true">↗</span></button></form></div></section>@endif
@endsection
