@extends('layouts.public')
@section('title', ($course->seo_title ?: $course->title) . ' — Mwanafunzi Investor')
@section('description', $course->seo_description ?: $course->short_description)
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Course', 'name' => $course->title, 'description' => $course->short_description, 'url' => route('courses.show', $course), 'provider' => ['@type' => 'Organization', 'name' => 'Mwanafunzi Investor']], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<section class="detail-hero"><div class="container narrow"><a class="back-link" href="{{ route('courses') }}">← All courses</a><p class="eyebrow"><span class="eyebrow-line"></span> {{ $course->level }} <span class="eyebrow-dot"></span> {{ $course->duration }}</p><h1>{{ $course->title }}</h1>@if($course->featured_image)<img class="detail-image" src="{{ asset('storage/'.$course->featured_image) }}" alt="{{ $course->title }}">@endif<p class="lede">{{ $course->short_description }}</p><div class="detail-actions"><span class="status-badge">{{ str_replace('_', ' ', $course->status) }}</span><a class="button button-accent" href="{{ route('contact') }}">{{ $course->cta_label ?: 'Ask about this course' }} <span aria-hidden="true">↗</span></a></div></div></section>
<section class="platform-section"><div class="container two-column detail-grid"><div><p class="eyebrow">About the course</p><div class="rich-copy">{!! \App\Support\RichText::render($course->full_description ?: $course->short_description) !!}</div>@if($course->learning_outcomes)<h2>What you will practise</h2><ul class="check-list">@foreach($course->learning_outcomes as $outcome)<li>{{ $outcome }}</li>@endforeach</ul>@endif</div><aside class="detail-card"><span class="eyebrow">Course notes</span><dl><div><dt>Level</dt><dd>{{ $course->level ?: 'To be confirmed' }}</dd></div><div><dt>Format</dt><dd>{{ $course->duration ?: 'To be confirmed' }}</dd></div><div><dt>Availability</dt><dd>{{ str_replace('_', ' ', $course->status) }}</dd></div></dl><p>No profitability guarantees. This is financial education, not personalised advice.</p></aside></div></section>
<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Curriculum</p><h2>What is covered</h2><div class="module-list">@forelse($course->modules as $module)<details><summary>{{ $module->title }} <span>+</span></summary><p>{{ $module->description }}</p>@foreach($module->lessons as $lesson)<div class="lesson-row">{{ $lesson->title }}</div>@endforeach</details>@empty<div class="empty-state compact"><h3>Curriculum is being prepared.</h3><p>We will publish the modules when they are ready to support a careful learning experience.</p></div>@endforelse</div></div></section>
@if($course->faqs->isNotEmpty())<section class="platform-section"><div class="container"><p class="eyebrow">Questions</p><h2>Course FAQs</h2><div class="module-list">@foreach($course->faqs as $faq)<details><summary>{{ $faq->question }} <span>+</span></summary><p>{{ $faq->answer }}</p></details>@endforeach</div></div></section>@endif
@endsection
