@extends('layouts.admin')
@section('title', 'Notifications')
@section('portal-heading', 'Notifications')
@section('content')
<x-admin.page-header eyebrow="Admin desk / Activity" title="Notifications" description="Keep track of real enquiry activity that needs the desk’s attention." />
<div class="admin-notification-toolbar"><nav class="admin-search-tabs" aria-label="Notification filters"><a class="{{ $filter === 'all' ? 'is-active' : '' }}" href="{{ route('admin.notifications', ['filter' => 'all']) }}">All</a><a class="{{ $filter === 'unread' ? 'is-active' : '' }}" href="{{ route('admin.notifications', ['filter' => 'unread']) }}">Unread</a></nav>@if($notifications->contains(fn ($notification) => ! $notification->read_at))<form method="post" action="{{ route('admin.notifications.read-all') }}">@csrf<button class="button button-secondary button-small" type="submit">Mark all as read</button></form>@endif</div>
<x-admin.card class="admin-notifications-card"><div class="admin-notification-page-list">@forelse($notifications as $notification)<article class="admin-notification-page-item {{ $notification->read_at ? '' : 'is-unread' }}"><span class="admin-notification-dot" aria-hidden="true"></span><div><strong>{{ $notification->name }} sent an enquiry</strong><p>{{ \Illuminate\Support\Str::limit($notification->message, 180) }}</p><small>{{ $notification->businessUnit?->name ?: 'General desk' }} · {{ $notification->created_at->diffForHumans() }}</small></div><div class="admin-notification-page-actions">@if(!$notification->read_at)<form method="post" action="{{ route('admin.notifications.read', $notification) }}">@csrf<button class="button button-ghost button-small" type="submit">Mark read</button></form>@endif<a class="button button-secondary button-small" href="{{ route('admin.messages.show', $notification) }}">Open <span aria-hidden="true">↗</span></a></div></article>@empty<x-admin.empty-state title="No notifications" description="New enquiry activity will appear here." />@endforelse</div></x-admin.card>
{{ $notifications->links() }}
@endsection
