@extends('layouts.public')
@php($ogImage = $topic->og_image ? \App\Support\PublicHero::candidate($topic->og_image) : null)
@section('title', ($topic->seo_title ?: $topic->title).' — Mwanafunzi Investor')
@section('description', $topic->seo_description ?: $topic->short_description)
@section('canonical', $topic->canonical_url ?: route('learn.show', $topic))
@section('robots', $topic->robots ?: 'index,follow')
@section('og_title', $topic->og_title ?: ($topic->seo_title ?: $topic->title))
@section('og_description', $topic->og_description ?: ($topic->seo_description ?: $topic->short_description))
@if($ogImage) @section('og_image', $ogImage['url']) @endif
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Course', 'name' => $topic->title, 'description' => $topic->short_description, 'url' => route('learn.show', $topic), 'image' => $ogImage['url'] ?? null, 'provider' => ['@type' => 'Organization', 'name' => \App\Models\SiteSetting::getValue('brand_name', 'Mwanafunzi Investor')]], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<x-public-hero class="detail-hero" compact :eyebrow="$topic->hero_eyebrow ?: trim(($topic->skill_level ?: 'Learning topic').' · '.($topic->study_time ?: 'Self-paced'))" :title="$topic->hero_title ?: $topic->title" :summary="$topic->hero_summary ?: $topic->short_description" :image="$topic->hero_image ?: $topic->image" :overlay="$topic->hero_overlay ?: 'medium'" :alignment="$topic->hero_alignment ?: 'left'" setting="hero_learn_image" :fallback-image="config('public.hero_defaults.learn')" :metadata="['Published learning path']" :breadcrumbs="[['label' => 'Learn', 'url' => route('learn')]]" />
<section class="platform-section"><div class="container two-column detail-grid"><div><p class="eyebrow">The learning path</p><div class="rich-copy">{!! \App\Support\RichText::render($topic->full_description ?: $topic->short_description) !!}</div>@if($topic->learning_outcomes)<h2>What you will practise</h2><ul class="check-list">@foreach($topic->learning_outcomes as $outcome)<li>{{ $outcome }}</li>@endforeach</ul>@endif</div><aside class="detail-card"><span class="eyebrow">Topic notes</span><dl><div><dt>Level</dt><dd>{{ $topic->skill_level ?: 'To be confirmed' }}</dd></div><div><dt>Study time</dt><dd>{{ $topic->study_time ?: 'Self-paced' }}</dd></div><div><dt>Courses</dt><dd>{{ $topic->courses->count() ?: 'None yet' }}</dd></div></dl></aside></div></section>
@if($topic->courses->isNotEmpty())<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Continue learning</p><h2>Courses connected to this path.</h2><div class="course-list">@foreach($topic->courses as $course)<a class="course-row" href="{{ route('courses.show', $course) }}"><span class="course-number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div class="course-name"><h3>{{ $course->title }}</h3><p>{{ $course->short_description }}</p></div><span class="course-arrow" aria-hidden="true">↗</span></a>@endforeach</div></div></section>@endif
@if($topic->articles->isNotEmpty())<section class="platform-section"><div class="container"><p class="eyebrow">Field notes</p><h2>Keep studying the context.</h2><div class="article-grid">@foreach($topic->articles as $article)<article class="article-card"><h2><a href="{{ route('journal.show', $article) }}">{{ $article->title }}</a></h2><p>{{ $article->excerpt }}</p><a class="text-link" href="{{ route('journal.show', $article) }}">Read the note <span aria-hidden="true">→</span></a></article>@endforeach</div></div></section>@endif
@if($topic->products->isNotEmpty())<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Useful tools</p><h2>Make the process visible.</h2><div class="platform-card-grid">@foreach($topic->products as $product)<a class="platform-card" href="{{ route('tools.show', $product) }}"><div class="card-top"><span class="eyebrow">{{ $product->product_type }}</span><span class="card-icon">↗</span></div><h2>{{ $product->name }}</h2><p>{{ $product->short_description }}</p></a>@endforeach</div></div></section>@endif
@if($topic->faqs->isNotEmpty())<section class="platform-section"><div class="container narrow"><p class="eyebrow">Questions</p><h2>About this path</h2><div class="module-list">@foreach($topic->faqs as $faq)<details><summary>{{ $faq->question }} <span>+</span></summary><p>{{ $faq->answer }}</p></details>@endforeach</div></div></section>@endif
@endsection
