@extends('layouts.admin')
@section('title', $title)
@section('portal-heading', 'Journal')
@section('content')
<x-admin.page-header eyebrow="{{ $eyebrow }}" title="{{ $title }}" description="Keep editorial classification clear, searchable and reusable." action-url="{{ route('admin.'.$kind.'.create') }}" action-label="New {{ $kind === 'categories' ? 'category' : 'tag' }}" />
<x-admin.filter-toolbar method="get" action="{{ route('admin.'.$kind) }}"><label class="admin-search-field"><span class="sr-only">Search {{ $kind }}</span><input type="search" name="q" value="{{ $term ?? request('q') }}" placeholder="Search name or slug"></label><button class="button button-secondary button-small" type="submit">Search</button>@if(request('q'))<a class="button button-ghost button-small" href="{{ route('admin.'.$kind) }}">Reset</a>@endif</x-admin.filter-toolbar>
<x-admin.card class="admin-table-card"><div class="admin-table admin-taxonomy-table"><div class="admin-table-head"><span>Name</span><span>Usage</span><span>Visibility</span><span>Actions</span></div>@forelse($items as $item)<div class="admin-table-row"><div><strong>{{ $item->name }}</strong><small>{{ $item->slug }}@if($item->description) · {{ \Illuminate\Support\Str::limit($item->description, 70) }}@endif</small></div><span>{{ $item->articles_count }} articles</span>@if($kind === 'categories')<x-admin.status-badge :status="$item->is_active ? 'active' : 'hidden'" />@else<span>Ready to use</span>@endif<x-admin.action-menu><a href="{{ route('admin.'.$kind.'.edit', $item) }}">Edit</a><form method="post" action="{{ route('admin.'. $kind . '.destroy', $item) }}" data-confirm="Remove this {{ $kind === 'categories' ? 'category' : 'tag' }}?">@csrf @method('delete')<button type="submit">Remove</button></form></x-admin.action-menu></div>@empty<x-admin.empty-state title="Nothing here yet." description="Create a reusable {{ $kind === 'categories' ? 'category' : 'tag' }} for your editorial workflow." action-url="{{ route('admin.'.$kind.'.create') }}" action-label="Create one" />@endforelse</div></x-admin.card>
{{ $items->withQueryString()->links() }}
@endsection
