@extends('layouts.public')
@section('title', $page?->seo_title ?: 'Privacy Policy — Mwanafunzi Investor')
@section('description', $page?->seo_description ?: 'How Mwanafunzi Investor handles account, contact, order and session information.')
@php
$sections = [
    ['id' => 'information-collected', 'title' => 'Information collected', 'paragraphs' => ['We collect information that is needed to operate the platform, respond to a request or provide a product or course.'], 'list' => ['Account details such as your name and email address when you register.', 'Contact details and the message you choose to send through the contact form.', 'Order, entitlement and payment-reference information connected to a purchase or enrolment.', 'Session and security information needed for sign-in, verification and basic site operation.']],
    ['id' => 'contact-submissions', 'title' => 'Contact submissions', 'paragraphs' => ['A contact message is used to understand and respond to the enquiry you submitted. It may be routed internally to the relevant Mwanafunzi Investor module so the right desk can follow up.'], 'callout' => 'Contact messages are not sold. Please do not include passwords, payment-card numbers or other information that is not needed for your enquiry.'],
    ['id' => 'orders-and-payments', 'title' => 'Orders and payment data', 'paragraphs' => ['When commerce is enabled, the platform keeps an order record, product or course snapshot, payment status and provider reference so that access, support and reconciliation can work. Payment-card details are handled by the configured payment provider rather than stored as plain card data by this site.']],
    ['id' => 'cookies-and-sessions', 'title' => 'Cookies and sessions', 'paragraphs' => ['The application uses essential cookies and sessions for authentication, security, form protection and remembering the state of a request. If optional analytics or marketing tools are added later, this policy should be updated before they are used.']],
    ['id' => 'use-and-sharing', 'title' => 'How information is used and shared', 'paragraphs' => ['Information is used to provide the requested platform function, respond to support, process orders, protect the site and improve the clarity of the service. Access is limited to people or providers who need it for those purposes, including configured payment or email services. We do not sell contact information.']],
    ['id' => 'retention-and-security', 'title' => 'Retention and security', 'paragraphs' => ['Records are kept for as long as they are needed for the purpose they were collected, account administration, support, financial reconciliation or a legitimate security need. The platform uses authentication, validation, access controls and private download routes, but no internet service can promise perfect security.']],
    ['id' => 'your-questions', 'title' => 'Your questions and requests', 'paragraphs' => ['You can contact the desk to ask what information is associated with your account or submission, request a correction, or ask a question about how information is handled. We will review the request in the context of the service and applicable requirements.']],
];
$related = ['terms' => 'Terms of use', 'risk-disclosure' => 'Risk disclosure', 'refund-policy' => 'Refund policy'];
@endphp
@section('content') @include('public.pages.legal-content', ['heading' => 'Privacy policy', 'eyebrow' => 'Policies / Privacy', 'intro' => 'We collect only the information needed to respond to enquiries, operate accounts and orders, and improve this platform. Contact messages are used for the purpose you submit them for and are not sold.', 'sections' => $sections, 'related' => $related, 'supportCopy' => 'If you have a question about a contact submission, account record or order record, contact the Mwanafunzi Investor desk.']) @endsection
