@extends('layouts.public')
@section('title', $page?->seo_title ?: 'Risk Disclosure — Mwanafunzi Investor')
@section('description', $page?->seo_description ?: 'A clear explanation of trading risk, educational content and responsible use of Mwanafunzi Investor tools.')
@php
$sections = [
    ['id' => 'educational-purpose', 'title' => 'Educational purpose', 'paragraphs' => ['Mwanafunzi Investor provides general education about markets, probability, trading systems, risk planning and disciplined decision-making. Nothing on this site is personalised financial advice or a recommendation to buy or sell an asset.']],
    ['id' => 'general-trading-risk', 'title' => 'General trading risk', 'paragraphs' => ['Trading and investing involve uncertainty. Prices can move against you, assumptions can be wrong, and a strategy that worked in one period may not work in another. You can lose part or all of the capital you put at risk.']],
    ['id' => 'leverage-and-capital-loss', 'title' => 'Leveraged products and capital loss', 'paragraphs' => ['Leverage can increase both gains and losses and may cause losses to develop quickly. Only use capital you can responsibly afford to lose, and understand the rules, costs and risks of the platform or broker you choose.']],
    ['id' => 'no-guarantees', 'title' => 'No guaranteed returns', 'paragraphs' => ['No return, level of income or trading result is guaranteed. Past performance, examples, case studies and hypothetical illustrations do not guarantee future results.']],
    ['id' => 'simulated-results', 'title' => 'Simulated or hypothetical results', 'paragraphs' => ['A backtest, model, calculator or hypothetical example may not reflect real execution, liquidity, fees, slippage, taxes or the emotional pressure of live decisions. Treat such material as an educational illustration, not a prediction.']],
    ['id' => 'tools-and-calculators', 'title' => 'Tools and calculators', 'paragraphs' => ['Tools are provided to help make a process visible. Check inputs, assumptions and outputs independently before relying on them. A calculator cannot decide whether a trade or investment is appropriate for you.']],
    ['id' => 'user-responsibility', 'title' => 'User responsibility', 'paragraphs' => ['You are responsible for your own decisions, account security, position sizing, records and professional advice. Consider your financial circumstances and seek independent qualified advice where appropriate.']],
    ['id' => 'third-party-platforms', 'title' => 'Third-party platforms', 'paragraphs' => ['Broker, exchange, payment, charting and other third-party services have their own terms, technology and risks. Mwanafunzi Investor does not control their availability, pricing, execution or data.']],
    ['id' => 'changes', 'title' => 'Changes to this disclosure', 'paragraphs' => ['This disclosure may be updated as the platform, products and educational material develop. The current version is the one published on this page.']],
];
$related = ['disclaimer' => 'Educational disclaimer', 'terms' => 'Terms of use', 'privacy-policy' => 'Privacy policy'];
@endphp
@section('content') @include('public.pages.legal-content', ['heading' => 'Risk disclosure', 'eyebrow' => 'Policies / Risk', 'intro' => 'Mwanafunzi Investor content is for educational purposes only and is not personalised financial advice. Trading involves risk, and leveraged trading can result in the loss of capital. No return is guaranteed, and past performance does not guarantee future results.', 'sections' => $sections, 'related' => $related, 'supportHeading' => 'Understand the risk before you trade.', 'supportCopy' => 'Questions about this disclosure? Contact the Mwanafunzi Investor desk before using educational material or tools.']) @endsection
