@extends('layouts.public')
@section('title', $page?->seo_title ?: 'Terms — Mwanafunzi Investor')
@section('description', $page?->seo_description ?: 'Terms for using the Mwanafunzi Investor website, courses, tools and account areas.')
@php
$sections = [
    ['id' => 'acceptance', 'title' => 'Acceptance of terms', 'paragraphs' => ['This website provides educational information, learning material and tools in development. By using it, you agree to use the platform responsibly and to follow these terms. If you do not agree, please do not use the platform.']],
    ['id' => 'educational-content', 'title' => 'Educational nature of content', 'paragraphs' => ['Mwanafunzi Investor content is general education about markets, probability, systems and risk. It is not personalised financial advice, an instruction to trade, or a promise of a particular outcome. You are responsible for deciding whether any information is suitable for your circumstances.']],
    ['id' => 'user-responsibilities', 'title' => 'User responsibilities', 'paragraphs' => ['Use the platform lawfully, provide accurate information where an account or order requires it, and keep your sign-in details private. Do not use the service to interfere with its operation, misrepresent another person or attempt to access information that is not yours.']],
    ['id' => 'accounts', 'title' => 'Account use', 'paragraphs' => ['Some course, product and download functions require a verified account. The account area is for the registered user and may show only the courses, orders and entitlements associated with that account.']],
    ['id' => 'digital-products', 'title' => 'Digital products and course access', 'paragraphs' => ['A product or course page should state its availability, description and access conditions before checkout or enrolment. Access is tied to the order or enrolment record created by the platform and may be affected if an order is cancelled or refunded.']],
    ['id' => 'payments-and-refunds', 'title' => 'Payments and refunds', 'paragraphs' => ['Payment status and provider references are recorded to support checkout and reconciliation. Refund questions are handled under the Refund Policy and any specific terms shown with the relevant product or course.']],
    ['id' => 'intellectual-property', 'title' => 'Intellectual property', 'paragraphs' => ['The site structure, original writing, course material, tools, marks and other content belong to Mwanafunzi Investor or the relevant rights holder. You may use content for personal learning within the access granted to you, but do not copy, resell, redistribute or present it as your own without permission.']],
    ['id' => 'prohibited-use', 'title' => 'Prohibited use', 'paragraphs' => ['Do not scrape private areas, bypass access controls, upload harmful code, misuse another user’s account, or use the platform to make misleading financial claims.']],
    ['id' => 'availability-and-changes', 'title' => 'Availability and changes', 'paragraphs' => ['The platform, content and catalogue may change as the work develops. We may add, remove or revise material, pause a feature, or correct an error. Changes to these terms will be reflected on this page when they are made.']],
];
$related = ['privacy-policy' => 'Privacy policy', 'risk-disclosure' => 'Risk disclosure', 'refund-policy' => 'Refund policy'];
@endphp
@section('content') @include('public.pages.legal-content', ['heading' => 'Terms of use', 'eyebrow' => 'Policies / Terms', 'intro' => 'This website provides educational information and tools in development. By using it, you agree to use the content responsibly and understand that availability may change.', 'sections' => $sections, 'related' => $related, 'supportCopy' => 'If a term or a course, product or account condition is unclear, contact the Mwanafunzi Investor desk before relying on it.']) @endsection
