@extends('layouts.admin')
@section('title', $service->exists ? 'Edit service' : 'Add service')
@section('portal-heading', 'Services')
@section('content')
<x-admin.page-header eyebrow="Portfolio / Services" title="{{ $service->exists ? 'Edit service' : 'Add service' }}" description="Keep pricing optional and factual. Empty pricing fields render as Custom quote on the public site." />
<form class="admin-form admin-editor-form" method="post" action="{{ $action }}">@csrf @if($service->exists) @method('put') @endif
<x-admin.form-section title="Service identity"><div class="form-row"><label>Title<input name="title" value="{{ old('title', $service->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $service->slug) }}" required></label></div><div class="form-row"><label>Business module<select name="business_unit_id"><option value="">Shared / not assigned</option>@foreach($businessUnits as $businessUnit)<option value="{{ $businessUnit->id }}" @selected((int) old('business_unit_id', $service->business_unit_id) === $businessUnit->id)>{{ $businessUnit->name }}</option>@endforeach</select><small class="field-help">Assign this service so it appears only in the correct public service area.</small></label><label>Icon or label<input name="icon" value="{{ old('icon', $service->icon) }}" placeholder="Optional mark or short label"></label></div><label>Short description<textarea name="short_description" rows="3" required>{{ old('short_description', $service->short_description) }}</textarea></label><label>Detailed description<textarea name="detailed_description" rows="8">{{ old('detailed_description', $service->detailed_description) }}</textarea><small class="field-help">Rich text is sanitized before saving.</small></label><div class="form-row"><x-admin.media-field name="featured_image" label="Featured image" :value="$service->featured_image" :media="$media" /></div></x-admin.form-section>
<x-admin.form-section title="Pricing and delivery"><div class="form-row"><label>Pricing type<select name="pricing_type"><option value="custom_quote" @selected(old('pricing_type', $service->pricing_type) === 'custom_quote')>Custom quote</option><option value="starting_from" @selected(old('pricing_type', $service->pricing_type) === 'starting_from')>Starting from</option><option value="fixed" @selected(old('pricing_type', $service->pricing_type) === 'fixed')>Fixed</option><option value="hourly" @selected(old('pricing_type', $service->pricing_type) === 'hourly')>Hourly</option><option value="project_based" @selected(old('pricing_type', $service->pricing_type) === 'project_based')>Project based</option></select></label><label>Starting price<input type="number" min="0" step="0.01" name="starting_price" value="{{ old('starting_price', $service->starting_price) }}" placeholder="Leave empty if not configured"></label></div><div class="form-row"><label>Currency<input name="currency" value="{{ old('currency', $service->currency ?: 'TZS') }}" maxlength="3"></label><label>Pricing label<input name="pricing_label" value="{{ old('pricing_label', $service->pricing_label) }}" placeholder="Optional override"></label></div><label>Typical delivery<input name="delivery_estimate" value="{{ old('delivery_estimate', $service->delivery_estimate) }}" placeholder="e.g. 3–8 weeks"></label><label>Included features <span>(one per line)</span><textarea name="included_features" rows="6">{{ old('included_features', collect($service->included_features ?: [])->implode("\n")) }}</textarea></label></x-admin.form-section>
<x-admin.form-section title="Publishing and CTA"><div class="form-row"><label>CTA label<input name="cta_label" value="{{ old('cta_label', $service->cta_label) }}"></label><label>CTA URL<input name="cta_url" value="{{ old('cta_url', $service->cta_url) }}" placeholder="/contact or https://..."></label></div><div class="form-row"><label>Display order<input type="number" min="0" name="sort_order" value="{{ old('sort_order', $service->sort_order) }}" required></label><x-admin.toggle name="is_featured" label="Featured on public surfaces" :checked="old('is_featured', $service->is_featured) == true" /><x-admin.toggle name="is_active" label="Active and visible" :checked="old('is_active', $service->is_active) == true" /></div></x-admin.form-section>
<x-admin.form-section title="Related projects"><fieldset class="form-section"><legend>Case studies</legend><div class="admin-check-grid">@forelse($projects as $project)<label class="admin-check"><input type="checkbox" name="project_ids[]" value="{{ $project->id }}" @checked(in_array($project->id, old('project_ids', $service->projects->pluck('id')->all()), true))><span>{{ $project->title }}</span></label>@empty<p class="field-help">Projects can be related here after they have been added.</p>@endforelse</div></fieldset></x-admin.form-section>
<x-admin.form-section title="SEO"><div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $service->seo_title) }}"></label><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $service->canonical_url) }}"></label></div><label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $service->seo_description) }}</textarea></label><div class="form-row"><label>Robots<select name="robots"><option value="index,follow" @selected(old('robots', $service->robots ?: 'index,follow') === 'index,follow')>Index, follow</option><option value="noindex,nofollow" @selected(old('robots', $service->robots) === 'noindex,nofollow')>No index</option></select></label><x-admin.media-field name="og_image" label="Open Graph image" :value="$service->og_image" :media="$media" /></div></x-admin.form-section>
<div class="admin-form-actions"><button class="button button-primary" type="submit">Save service <span aria-hidden="true">↗</span></button><a class="button button-secondary" href="{{ route('admin.services') }}">Cancel</a></div>
</form>
@endsection
