<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PublicSiteController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\SiteSettingsController;
use App\Http\Controllers\AdminTaxonomyController;
use App\Http\Controllers\CustomerAuthController;
use App\Http\Controllers\CustomerAccountController;
use App\Http\Controllers\CommerceController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\WaitlistController;
use App\Http\Controllers\AdminCommerceController;
use App\Http\Controllers\AdminPageController;
use App\Http\Controllers\AdminNavigationController;
use App\Http\Controllers\AdminAuditController;
use App\Http\Controllers\AdminSearchController;
use App\Http\Controllers\AdminFaqController;
use App\Http\Controllers\AdminRedirectController;
use App\Http\Controllers\PublicRedirectController;
use App\Http\Controllers\AdminBusinessUnitController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\AdminCustomerController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\AdminNotificationController;
use App\Http\Controllers\AdminServiceController;
use App\Http\Controllers\AdminProjectController;
use App\Http\Controllers\AdminTestimonialController;
use App\Http\Controllers\AdminTeamMemberController;
use App\Http\Controllers\AdminCommentController;
use App\Http\Controllers\EditorialInteractionController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

Route::controller(PublicSiteController::class)->group(function () {
    Route::get('/', 'home')->name('home');
    Route::get('/financial-academy', 'academy')->name('forex-academy');
    Route::get('/digital-software', 'module')->defaults('slug', 'development')->name('digital-systems');
    Route::get('/digital-software/products', 'moduleCollection')->defaults('slug', 'development')->defaults('collection', 'products')->name('digital-software.products');
    Route::get('/digital-software/projects', 'moduleCollection')->defaults('slug', 'development')->defaults('collection', 'projects')->name('digital-software.projects');
    Route::get('/digital-software/testimonials', 'moduleCollection')->defaults('slug', 'development')->defaults('collection', 'testimonials')->name('digital-software.testimonials');
    Route::redirect('/digital-systems', '/digital-software', 301)->name('digital-systems.legacy');
    Route::get('/creative-studio', 'module')->defaults('slug', 'studio')->name('creative-studio');
    Route::get('/creative-studio/services', 'moduleCollection')->defaults('slug', 'studio')->defaults('collection', 'services')->name('creative-studio.services');
    Route::get('/creative-studio/projects', 'moduleCollection')->defaults('slug', 'studio')->defaults('collection', 'projects')->name('creative-studio.projects');
    Route::get('/creative-studio/testimonials', 'moduleCollection')->defaults('slug', 'studio')->defaults('collection', 'testimonials')->name('creative-studio.testimonials');
    Route::get('/development', 'module')->defaults('slug', 'development')->name('development');
    Route::get('/studio', 'module')->defaults('slug', 'studio')->name('studio');
    Route::get('/services', 'services')->name('services');
    Route::get('/services/{service:slug}', 'service')->name('services.show');
    Route::get('/projects', 'projects')->name('projects');
    Route::get('/projects/{project:slug}', 'project')->name('projects.show');
    Route::get('/financial-academy/learn', 'learn')->name('learn');
    Route::get('/financial-academy/learn/{topic:slug}', 'topic')->name('learn.show');
    Route::get('/financial-academy/courses', 'courses')->name('courses');
    Route::get('/financial-academy/courses/{course:slug}', 'course')->name('courses.show');
    Route::get('/financial-academy/tools', 'tools')->name('tools');
    Route::get('/financial-academy/tools/{product:slug}', 'tool')->name('tools.show');
    Route::get('/journal', 'journal')->name('journal');
    Route::get('/journal/category/{category:slug}', 'journalCategory')->name('journal.category');
    Route::get('/journal/tag/{tag:slug}', 'journalTag')->name('journal.tag');
    Route::get('/journal/author/{member:slug}', 'journalAuthor')->name('journal.author');
    Route::get('/journal/{article:slug}', 'article')->name('journal.show');
    Route::get('/feed', 'feed')->name('feed');
    Route::get('/about/team/{member}', 'teamMember')->name('team.show');
    Route::get('/about', 'page')->defaults('page', 'about')->name('about');
    Route::get('/student-of-money', 'page')->defaults('page', 'student-of-money')->name('student-of-money');
    Route::get('/pages/{slug}', 'pageBySlug')->name('pages.show');
    Route::get('/contact', 'contact')->name('contact');
    Route::post('/contact', 'submitContact')->middleware('throttle:10,1')->name('contact.submit');
    Route::post('/journal/{article}/reaction', [EditorialInteractionController::class, 'react'])->middleware(['auth', 'throttle:30,1'])->name('journal.reaction');
    Route::post('/journal/{article}/comments', [EditorialInteractionController::class, 'comment'])->middleware(['auth', 'throttle:5,5'])->name('journal.comments.store');
    Route::post('/comments/{comment}/report', [EditorialInteractionController::class, 'report'])->middleware(['auth', 'throttle:10,10'])->name('comments.report');
    Route::get('/sitemap.xml', 'sitemap')->name('sitemap');
    Route::get('/{page}', 'page')->whereIn('page', ['privacy-policy', 'terms', 'risk-disclosure', 'refund-policy', 'disclaimer'])->name('legal');
});

// Legacy public URLs redirect to the classified Financial Academy namespace.
Route::redirect('/forex-academy', '/financial-academy', 301)->name('forex-academy.legacy');
Route::redirect('/learn', '/financial-academy/learn', 301)->name('learn.legacy');
Route::get('/learn/{topic:slug}', fn (\App\Models\LearningTopic $topic) => redirect()->route('learn.show', $topic, 301))->name('learn.legacy.show');
Route::redirect('/courses', '/financial-academy/courses', 301)->name('courses.legacy');
Route::get('/courses/{course:slug}', fn (\App\Models\Course $course) => redirect()->route('courses.show', $course, 301))->name('courses.legacy.show');
Route::redirect('/tools', '/financial-academy/tools', 301)->name('tools.legacy');
Route::get('/tools/{product:slug}', fn (\App\Models\Product $product) => redirect()->route('tools.show', $product, 301))->name('tools.legacy.show');

Route::get('/health', function () {
    try {
        DB::connection()->getPdo();

        return response()->json(['status' => 'ok']);
    } catch (Throwable) {
        return response()->json(['status' => 'unavailable'], 503);
    }
})->name('health');

Route::get('/robots.txt', function () {
    return response("User-agent: *\nDisallow:\nSitemap: ".url('/sitemap.xml')."\n", 200, ['Content-Type' => 'text/plain; charset=UTF-8']);
})->name('robots');

Route::get('/login', [CustomerAuthController::class, 'login'])->name('login');
Route::post('/login', [CustomerAuthController::class, 'storeLogin'])->middleware('throttle:5,1')->name('login.store');
Route::get('/register', [CustomerAuthController::class, 'register'])->name('register');
Route::post('/register', [CustomerAuthController::class, 'storeRegister'])->middleware('throttle:5,1')->name('register.store');
Route::get('/email/verify', [CustomerAuthController::class, 'verificationNotice'])->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', [CustomerAuthController::class, 'verify'])->middleware(['auth', 'signed', 'throttle:6,1'])->name('verification.verify');
Route::post('/email/verification-notification', [CustomerAuthController::class, 'resendVerification'])->middleware(['auth', 'throttle:3,1'])->name('verification.send');
Route::post('/logout', [CustomerAuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/checkout/product/{product:slug}', [CommerceController::class, 'productCheckout'])->name('checkout.product');
    Route::post('/checkout/product/{product:slug}', [CommerceController::class, 'storeProduct'])->middleware('throttle:8,1')->name('checkout.product.store');
    Route::get('/checkout/course/{course:slug}', [CommerceController::class, 'courseCheckout'])->name('checkout.course');
    Route::post('/checkout/course/{course:slug}', [CommerceController::class, 'storeCourse'])->middleware('throttle:8,1')->name('checkout.course.store');
    Route::get('/payments/success/{order:order_number}', [CommerceController::class, 'success'])->name('payments.success');
    Route::get('/payments/failure/{order:order_number}', [CommerceController::class, 'failure'])->name('payments.failure');
    Route::get('/payments/processing/{order:order_number}', [CommerceController::class, 'processing'])->name('payments.processing');
    Route::get('/payments/sandbox/{payment}', [CommerceController::class, 'sandbox'])->name('payments.sandbox');
    Route::post('/payments/sandbox/{payment}', [CommerceController::class, 'completeSandbox'])->name('payments.sandbox.complete');
    Route::get('/payments/flutterwave/return', [CommerceController::class, 'flutterwaveReturn'])->name('payments.flutterwave.return');
    Route::get('/downloads/{asset}', DownloadController::class)->middleware('signed')->name('downloads.asset');
});
Route::post('/payments/flutterwave/webhook', [CommerceController::class, 'flutterwaveWebhook'])->name('payments.flutterwave.webhook');
Route::post('/financial-academy/courses/{course:slug}/waitlist', [WaitlistController::class, 'store'])->middleware('throttle:8,1')->name('courses.waitlist');
Route::post('/courses/{course:slug}/waitlist', [WaitlistController::class, 'store'])->middleware('throttle:8,1')->name('courses.waitlist.legacy');

Route::middleware(['auth'])->prefix('account')->name('account.')->group(function () {
    Route::get('/', [CustomerAccountController::class, 'dashboard'])->name('dashboard');
    Route::get('/orders', [CustomerAccountController::class, 'orders'])->name('orders');
    Route::get('/orders/{order}', [CustomerAccountController::class, 'order'])->name('orders.show');
    Route::get('/orders/{order}/receipt', [CustomerAccountController::class, 'receipt'])->name('orders.receipt');
    Route::get('/downloads', [CustomerAccountController::class, 'downloads'])->name('downloads');
    Route::get('/courses', [CustomerAccountController::class, 'courses'])->name('courses');
    Route::get('/courses/{enrollment}', [CustomerAccountController::class, 'course'])->name('courses.show');
    Route::get('/profile', [CustomerAccountController::class, 'profile'])->name('profile');
    Route::put('/profile', [CustomerAccountController::class, 'updateProfile'])->name('profile.update');
    Route::post('/profile/avatar', [CustomerAccountController::class, 'updateAvatar'])->name('profile.avatar.update');
    Route::delete('/profile/avatar', [CustomerAccountController::class, 'removeAvatar'])->name('profile.avatar.remove');
    Route::get('/security', [CustomerAccountController::class, 'security'])->name('security');
    Route::put('/security/password', [CustomerAccountController::class, 'updatePassword'])->name('security.password');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [AdminAuthController::class, 'create'])->name('login');
    Route::post('/login', [AdminAuthController::class, 'store'])->middleware('throttle:5,1')->name('login.store');
    Route::post('/logout', [AdminAuthController::class, 'destroy'])->middleware('auth')->name('logout');

    Route::middleware(['auth', 'admin'])->group(function () {
        Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::get('/preview/{type}/{id}', [PublicSiteController::class, 'preview'])->middleware('signed')->name('preview');
        Route::get('/courses', [AdminController::class, 'courses'])->name('courses');
        Route::get('/courses/create', [AdminController::class, 'courseCreate'])->name('courses.create');
        Route::post('/courses', [AdminController::class, 'courseStore'])->name('courses.store');
        Route::get('/courses/{course}/edit', [AdminController::class, 'courseEdit'])->name('courses.edit');
        Route::put('/courses/{course}', [AdminController::class, 'courseUpdate'])->name('courses.update');
        Route::delete('/courses/{course}', [AdminController::class, 'courseDestroy'])->name('courses.destroy');
        Route::post('/courses/{course}/restore', [AdminController::class, 'courseRestore'])->name('courses.restore');
        Route::post('/courses/{course}/modules', [AdminController::class, 'moduleStore'])->name('courses.modules.store');
        Route::put('/modules/{module}', [AdminController::class, 'moduleUpdate'])->name('modules.update');
        Route::delete('/modules/{module}', [AdminController::class, 'moduleDestroy'])->name('modules.destroy');
        Route::post('/modules/{module}/restore', [AdminController::class, 'moduleRestore'])->name('modules.restore');
        Route::post('/modules/{module}/lessons', [AdminController::class, 'lessonStore'])->name('modules.lessons.store');
        Route::put('/lessons/{lesson}', [AdminController::class, 'lessonUpdate'])->name('lessons.update');
        Route::delete('/lessons/{lesson}', [AdminController::class, 'lessonDestroy'])->name('lessons.destroy');
        Route::post('/lessons/{lesson}/restore', [AdminController::class, 'lessonRestore'])->name('lessons.restore');
        Route::post('/courses/{course}/faqs', [AdminController::class, 'courseFaqStore'])->name('courses.faqs.store');
        Route::delete('/course-faqs/{faq}', [AdminController::class, 'courseFaqDestroy'])->name('course-faqs.destroy');
        Route::get('/products', [AdminController::class, 'products'])->name('products');
        Route::get('/products/create', [AdminController::class, 'productCreate'])->name('products.create');
        Route::post('/products', [AdminController::class, 'productStore'])->name('products.store');
        Route::get('/products/{product}/edit', [AdminController::class, 'productEdit'])->name('products.edit');
        Route::put('/products/{product}', [AdminController::class, 'productUpdate'])->name('products.update');
        Route::delete('/products/{product}', [AdminController::class, 'productDestroy'])->name('products.destroy');
        Route::post('/products/{product}/restore', [AdminController::class, 'productRestore'])->name('products.restore');
        Route::post('/products/{product}/features', [AdminController::class, 'featureStore'])->name('products.features.store');
        Route::delete('/features/{feature}', [AdminController::class, 'featureDestroy'])->name('features.destroy');
        Route::post('/products/{product}/versions', [AdminController::class, 'versionStore'])->name('products.versions.store');
        Route::delete('/versions/{version}', [AdminController::class, 'versionDestroy'])->name('versions.destroy');
        Route::post('/products/{product}/faqs', [AdminController::class, 'productFaqStore'])->name('products.faqs.store');
        Route::delete('/faqs/{faq}', [AdminController::class, 'productFaqDestroy'])->name('faqs.destroy');
        Route::post('/products/{product}/images', [AdminController::class, 'productImageStore'])->name('products.images.store');
        Route::delete('/product-images/{image}', [AdminController::class, 'productImageDestroy'])->name('product-images.destroy');
        Route::get('/articles', [AdminController::class, 'articles'])->name('articles');
        Route::get('/articles/create', [AdminController::class, 'articleCreate'])->name('articles.create');
        Route::post('/articles', [AdminController::class, 'articleStore'])->name('articles.store');
        Route::get('/articles/{article}/edit', [AdminController::class, 'articleEdit'])->name('articles.edit');
        Route::put('/articles/{article}', [AdminController::class, 'articleUpdate'])->name('articles.update');
        Route::delete('/articles/{article}', [AdminController::class, 'articleDestroy'])->name('articles.destroy');
        Route::post('/articles/{article}/restore', [AdminController::class, 'articleRestore'])->name('articles.restore');
        Route::get('/journal', [AdminController::class, 'articles'])->name('journal');
        Route::get('/journal/create', [AdminController::class, 'articleCreate'])->name('journal.create');
        Route::post('/journal', [AdminController::class, 'articleStore'])->name('journal.store');
        Route::get('/journal/daily-updates/create', [AdminController::class, 'dailyUpdateCreate'])->name('journal.daily-updates.create');
        Route::post('/journal/daily-updates', [AdminController::class, 'dailyUpdateStore'])->name('journal.daily-updates.store');
        Route::get('/comments', [AdminCommentController::class, 'index'])->name('comments');
        Route::get('/comments/{comment}', [AdminCommentController::class, 'show'])->name('comments.show');
        Route::patch('/comments/{comment}', [AdminCommentController::class, 'update'])->name('comments.update');
        Route::delete('/comments/{comment}', [AdminCommentController::class, 'destroy'])->name('comments.destroy');
        Route::get('/messages', [AdminController::class, 'messages'])->name('messages');
        Route::get('/messages/{message}', [AdminController::class, 'messageShow'])->name('messages.show');
        Route::patch('/messages/{message}', [AdminController::class, 'messageUpdate'])->name('messages.update');
        Route::post('/messages/{message}/read', [AdminController::class, 'messageRead'])->name('messages.read');
        Route::get('/topics', [AdminController::class, 'topics'])->name('topics');
        Route::get('/topics/create', [AdminController::class, 'topicCreate'])->name('topics.create');
        Route::post('/topics', [AdminController::class, 'topicStore'])->name('topics.store');
        Route::get('/topics/{topic}/edit', [AdminController::class, 'topicEdit'])->name('topics.edit');
        Route::put('/topics/{topic}', [AdminController::class, 'topicUpdate'])->name('topics.update');
        Route::get('/faqs', [AdminFaqController::class, 'index'])->name('faqs');
        Route::post('/faqs', [AdminFaqController::class, 'store'])->name('faqs.store');
        Route::put('/faqs/{source}/{id}', [AdminFaqController::class, 'update'])->whereNumber('id')->name('faqs.update');
        Route::delete('/faqs/{source}/{id}', [AdminFaqController::class, 'destroy'])->whereNumber('id')->name('faqs.manage.destroy');
        Route::get('/media/search', [MediaController::class, 'search'])->name('media.search');
        Route::get('/media', [MediaController::class, 'index'])->name('media');
        Route::post('/media', [MediaController::class, 'store'])->name('media.store');
        Route::put('/media/{media}', [MediaController::class, 'update'])->name('media.update');
        Route::delete('/media/{media}', [MediaController::class, 'destroy'])->name('media.destroy');
        Route::get('/settings', [SiteSettingsController::class, 'edit'])->name('settings');
        Route::put('/settings', [SiteSettingsController::class, 'update'])->name('settings.update');
        Route::get('/business-units', [AdminBusinessUnitController::class, 'index'])->name('business-units');
        Route::put('/business-units/{businessUnit}', [AdminBusinessUnitController::class, 'update'])->name('business-units.update');
        Route::get('/audit', [AdminAuditController::class, 'index'])->name('audit');
        Route::get('/search', [AdminSearchController::class, 'index'])->name('search');
        Route::get('/search/suggestions', [AdminSearchController::class, 'suggestions'])->name('search.suggestions');
        Route::get('/notifications', [AdminNotificationController::class, 'index'])->name('notifications');
        Route::post('/notifications/read-all', [AdminNotificationController::class, 'readAll'])->name('notifications.read-all');
        Route::post('/notifications/{message}/read', [AdminNotificationController::class, 'read'])->name('notifications.read');
        Route::get('/profile', [AdminProfileController::class, 'show'])->name('profile');
        Route::put('/profile', [AdminProfileController::class, 'update'])->name('profile.update');
        Route::post('/profile/avatar', [AdminProfileController::class, 'updateAvatar'])->name('profile.avatar.update');
        Route::delete('/profile/avatar', [AdminProfileController::class, 'removeAvatar'])->name('profile.avatar.remove');
        Route::put('/profile/password', [AdminProfileController::class, 'updatePassword'])->name('profile.password');
        Route::get('/administrators', [AdminUserController::class, 'index'])->name('administrators');
        Route::get('/administrators/create', [AdminUserController::class, 'create'])->name('administrators.create');
        Route::post('/administrators', [AdminUserController::class, 'store'])->name('administrators.store');
        Route::get('/administrators/{administrator}/edit', [AdminUserController::class, 'edit'])->name('administrators.edit');
        Route::put('/administrators/{administrator}', [AdminUserController::class, 'update'])->name('administrators.update');
        Route::get('/customers', [AdminCustomerController::class, 'index'])->name('customers');
        Route::get('/customers/{customer}', [AdminCustomerController::class, 'show'])->name('customers.show');
        Route::patch('/customers/{customer}/status', [AdminCustomerController::class, 'updateStatus'])->name('customers.status');
        Route::get('/pages', [AdminPageController::class, 'index'])->name('pages');
        Route::get('/policies', [AdminPageController::class, 'policies'])->name('policies');
        Route::get('/redirects', [AdminRedirectController::class, 'index'])->name('redirects');
        Route::post('/redirects', [AdminRedirectController::class, 'store'])->name('redirects.store');
        Route::put('/redirects/{redirect}', [AdminRedirectController::class, 'update'])->name('redirects.update');
        Route::delete('/redirects/{redirect}', [AdminRedirectController::class, 'destroy'])->name('redirects.destroy');
        Route::get('/pages/create', [AdminPageController::class, 'create'])->name('pages.create');
        Route::post('/pages', [AdminPageController::class, 'store'])->name('pages.store');
        Route::get('/pages/{page}/edit', [AdminPageController::class, 'edit'])->name('pages.edit');
        Route::put('/pages/{page}', [AdminPageController::class, 'update'])->name('pages.update');
        Route::get('/navigation', [AdminNavigationController::class, 'index'])->name('navigation');
        Route::post('/navigation', [AdminNavigationController::class, 'store'])->name('navigation.store');
        Route::put('/navigation/{navigationItem}', [AdminNavigationController::class, 'update'])->name('navigation.update');
        Route::delete('/navigation/{navigationItem}', [AdminNavigationController::class, 'destroy'])->name('navigation.destroy');
        Route::get('/categories', [AdminTaxonomyController::class, 'categories'])->name('categories');
        Route::get('/categories/create', [AdminTaxonomyController::class, 'categoryCreate'])->name('categories.create');
        Route::post('/categories', [AdminTaxonomyController::class, 'categoryStore'])->name('categories.store');
        Route::get('/categories/{category}/edit', [AdminTaxonomyController::class, 'categoryEdit'])->name('categories.edit');
        Route::put('/categories/{category}', [AdminTaxonomyController::class, 'categoryUpdate'])->name('categories.update');
        Route::delete('/categories/{category}', [AdminTaxonomyController::class, 'categoryDestroy'])->name('categories.destroy');
        Route::get('/tags', [AdminTaxonomyController::class, 'tags'])->name('tags');
        Route::get('/tags/create', [AdminTaxonomyController::class, 'tagCreate'])->name('tags.create');
        Route::post('/tags', [AdminTaxonomyController::class, 'tagStore'])->name('tags.store');
        Route::get('/tags/{tag}/edit', [AdminTaxonomyController::class, 'tagEdit'])->name('tags.edit');
        Route::put('/tags/{tag}', [AdminTaxonomyController::class, 'tagUpdate'])->name('tags.update');
        Route::delete('/tags/{tag}', [AdminTaxonomyController::class, 'tagDestroy'])->name('tags.destroy');
        Route::get('/social-links', [AdminTaxonomyController::class, 'socialLinks'])->name('social-links');
        Route::post('/social-links', [AdminTaxonomyController::class, 'socialLinkStore'])->name('social-links.store');
        Route::put('/social-links/{socialLink}', [AdminTaxonomyController::class, 'socialLinkUpdate'])->name('social-links.update');
        Route::delete('/social-links/{socialLink}', [AdminTaxonomyController::class, 'socialLinkDestroy'])->name('social-links.destroy');
        Route::get('/services', [AdminServiceController::class, 'index'])->name('services');
        Route::get('/services/create', [AdminServiceController::class, 'create'])->name('services.create');
        Route::post('/services', [AdminServiceController::class, 'store'])->name('services.store');
        Route::get('/services/{service}/edit', [AdminServiceController::class, 'edit'])->name('services.edit');
        Route::put('/services/{service}', [AdminServiceController::class, 'update'])->name('services.update');
        Route::delete('/services/{service}', [AdminServiceController::class, 'destroy'])->name('services.destroy');
        Route::get('/projects', [AdminProjectController::class, 'index'])->name('projects');
        Route::get('/projects/create', [AdminProjectController::class, 'create'])->name('projects.create');
        Route::post('/projects', [AdminProjectController::class, 'store'])->name('projects.store');
        Route::get('/projects/{project}/edit', [AdminProjectController::class, 'edit'])->name('projects.edit');
        Route::put('/projects/{project}', [AdminProjectController::class, 'update'])->name('projects.update');
        Route::delete('/projects/{project}', [AdminProjectController::class, 'destroy'])->name('projects.destroy');
        Route::get('/testimonials', [AdminTestimonialController::class, 'index'])->name('testimonials');
        Route::get('/testimonials/create', [AdminTestimonialController::class, 'create'])->name('testimonials.create');
        Route::post('/testimonials', [AdminTestimonialController::class, 'store'])->name('testimonials.store');
        Route::get('/testimonials/{testimonial}/edit', [AdminTestimonialController::class, 'edit'])->name('testimonials.edit');
        Route::put('/testimonials/{testimonial}', [AdminTestimonialController::class, 'update'])->name('testimonials.update');
        Route::delete('/testimonials/{testimonial}', [AdminTestimonialController::class, 'destroy'])->name('testimonials.destroy');
        Route::get('/team', [AdminTeamMemberController::class, 'index'])->name('team');
        Route::get('/team/create', [AdminTeamMemberController::class, 'create'])->name('team.create');
        Route::post('/team', [AdminTeamMemberController::class, 'store'])->name('team.store');
        Route::get('/team/{teamMember}/edit', [AdminTeamMemberController::class, 'edit'])->name('team.edit');
        Route::put('/team/{teamMember}', [AdminTeamMemberController::class, 'update'])->name('team.update');
        Route::delete('/team/{teamMember}', [AdminTeamMemberController::class, 'destroy'])->name('team.destroy');
        Route::get('/commerce', [AdminCommerceController::class, 'dashboard'])->name('commerce.dashboard');
        Route::get('/commerce/orders', [AdminCommerceController::class, 'orders'])->name('commerce.orders');
        Route::get('/commerce/orders/{order}', [AdminCommerceController::class, 'order'])->name('commerce.orders.show');
        Route::post('/commerce/orders/{order}/refund', [AdminCommerceController::class, 'refund'])->name('commerce.orders.refund');
        Route::get('/commerce/payments', [AdminCommerceController::class, 'payments'])->name('commerce.payments');
        Route::get('/commerce/entitlements', [AdminCommerceController::class, 'entitlements'])->name('commerce.entitlements');
        Route::get('/commerce/enrollments', [AdminCommerceController::class, 'enrollments'])->name('commerce.enrollments');
        Route::get('/commerce/waitlists', [AdminCommerceController::class, 'waitlists'])->name('commerce.waitlists');
        Route::get('/commerce/waitlists/export', [AdminCommerceController::class, 'waitlistExport'])->name('commerce.waitlists.export');
        Route::post('/products/{product}/assets', [AdminCommerceController::class, 'assetStore'])->name('products.assets.store');
        Route::delete('/product-assets/{asset}', [AdminCommerceController::class, 'assetDestroy'])->name('product-assets.destroy');
    });
});

Route::get('/{path}', [PublicRedirectController::class, 'handle'])->where('path', '.*')->name('redirect.handle');
