<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PublicSiteController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\SiteSettingsController;
use App\Http\Controllers\AdminTaxonomyController;
use App\Http\Controllers\CustomerAuthController;
use App\Http\Controllers\CustomerAccountController;
use App\Http\Controllers\CommerceController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\WaitlistController;
use App\Http\Controllers\AdminCommerceController;
use App\Http\Controllers\AdminPageController;
use App\Http\Controllers\AdminNavigationController;
use App\Http\Controllers\AdminAuditController;
use App\Http\Controllers\AdminSearchController;
use App\Http\Controllers\AdminFaqController;
use Illuminate\Support\Facades\Route;

Route::controller(PublicSiteController::class)->group(function () {
    Route::get('/', 'home')->name('home');
    Route::get('/development', 'module')->defaults('slug', 'development')->name('development');
    Route::get('/studio', 'module')->defaults('slug', 'studio')->name('studio');
    Route::get('/learn', 'learn')->name('learn');
    Route::get('/courses', 'courses')->name('courses');
    Route::get('/courses/{course:slug}', 'course')->name('courses.show');
    Route::get('/tools', 'tools')->name('tools');
    Route::get('/tools/{product:slug}', 'tool')->name('tools.show');
    Route::get('/journal', 'journal')->name('journal');
    Route::get('/journal/{article:slug}', 'article')->name('journal.show');
    Route::get('/about', 'page')->defaults('page', 'about')->name('about');
    Route::get('/student-of-money', 'page')->defaults('page', 'student-of-money')->name('student-of-money');
    Route::get('/pages/{page:slug}', 'pageBySlug')->name('pages.show');
    Route::get('/contact', 'contact')->name('contact');
    Route::post('/contact', 'submitContact')->middleware('throttle:10,1')->name('contact.submit');
    Route::get('/sitemap.xml', 'sitemap')->name('sitemap');
    Route::get('/{page}', 'page')->whereIn('page', ['privacy-policy', 'terms', 'risk-disclosure', 'refund-policy', 'disclaimer'])->name('legal');
});

Route::get('/login', [CustomerAuthController::class, 'login'])->name('login');
Route::post('/login', [CustomerAuthController::class, 'storeLogin'])->middleware('throttle:5,1')->name('login.store');
Route::get('/register', [CustomerAuthController::class, 'register'])->name('register');
Route::post('/register', [CustomerAuthController::class, 'storeRegister'])->middleware('throttle:5,1')->name('register.store');
Route::get('/email/verify', [CustomerAuthController::class, 'verificationNotice'])->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', [CustomerAuthController::class, 'verify'])->middleware(['auth', 'signed', 'throttle:6,1'])->name('verification.verify');
Route::post('/email/verification-notification', [CustomerAuthController::class, 'resendVerification'])->middleware(['auth', 'throttle:3,1'])->name('verification.send');
Route::post('/logout', [CustomerAuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/checkout/product/{product:slug}', [CommerceController::class, 'productCheckout'])->name('checkout.product');
    Route::post('/checkout/product/{product:slug}', [CommerceController::class, 'storeProduct'])->middleware('throttle:8,1')->name('checkout.product.store');
    Route::get('/checkout/course/{course:slug}', [CommerceController::class, 'courseCheckout'])->name('checkout.course');
    Route::post('/checkout/course/{course:slug}', [CommerceController::class, 'storeCourse'])->middleware('throttle:8,1')->name('checkout.course.store');
    Route::get('/payments/success/{order:order_number}', [CommerceController::class, 'success'])->name('payments.success');
    Route::get('/payments/failure/{order:order_number}', [CommerceController::class, 'failure'])->name('payments.failure');
    Route::get('/payments/processing/{order:order_number}', [CommerceController::class, 'processing'])->name('payments.processing');
    Route::get('/payments/sandbox/{payment}', [CommerceController::class, 'sandbox'])->name('payments.sandbox');
    Route::post('/payments/sandbox/{payment}', [CommerceController::class, 'completeSandbox'])->name('payments.sandbox.complete');
    Route::get('/payments/flutterwave/return', [CommerceController::class, 'flutterwaveReturn'])->name('payments.flutterwave.return');
    Route::get('/downloads/{asset}', DownloadController::class)->middleware('signed')->name('downloads.asset');
});
Route::post('/payments/flutterwave/webhook', [CommerceController::class, 'flutterwaveWebhook'])->name('payments.flutterwave.webhook');
Route::post('/courses/{course:slug}/waitlist', [WaitlistController::class, 'store'])->middleware('throttle:8,1')->name('courses.waitlist');

Route::middleware(['auth'])->prefix('account')->name('account.')->group(function () {
    Route::get('/', [CustomerAccountController::class, 'dashboard'])->name('dashboard');
    Route::get('/orders', [CustomerAccountController::class, 'orders'])->name('orders');
    Route::get('/orders/{order}', [CustomerAccountController::class, 'order'])->name('orders.show');
    Route::get('/orders/{order}/receipt', [CustomerAccountController::class, 'receipt'])->name('orders.receipt');
    Route::get('/downloads', [CustomerAccountController::class, 'downloads'])->name('downloads');
    Route::get('/courses', [CustomerAccountController::class, 'courses'])->name('courses');
    Route::get('/courses/{enrollment}', [CustomerAccountController::class, 'course'])->name('courses.show');
    Route::get('/profile', [CustomerAccountController::class, 'profile'])->name('profile');
    Route::put('/profile', [CustomerAccountController::class, 'updateProfile'])->name('profile.update');
    Route::get('/security', [CustomerAccountController::class, 'security'])->name('security');
    Route::put('/security/password', [CustomerAccountController::class, 'updatePassword'])->name('security.password');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [AdminAuthController::class, 'create'])->name('login');
    Route::post('/login', [AdminAuthController::class, 'store'])->middleware('throttle:5,1')->name('login.store');
    Route::post('/logout', [AdminAuthController::class, 'destroy'])->middleware('auth')->name('logout');

    Route::middleware(['auth', 'admin'])->group(function () {
        Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::get('/preview/{type}/{id}', [PublicSiteController::class, 'preview'])->middleware('signed')->name('preview');
        Route::get('/courses', [AdminController::class, 'courses'])->name('courses');
        Route::get('/courses/create', [AdminController::class, 'courseCreate'])->name('courses.create');
        Route::post('/courses', [AdminController::class, 'courseStore'])->name('courses.store');
        Route::get('/courses/{course}/edit', [AdminController::class, 'courseEdit'])->name('courses.edit');
        Route::put('/courses/{course}', [AdminController::class, 'courseUpdate'])->name('courses.update');
        Route::delete('/courses/{course}', [AdminController::class, 'courseDestroy'])->name('courses.destroy');
        Route::post('/courses/{course}/restore', [AdminController::class, 'courseRestore'])->name('courses.restore');
        Route::post('/courses/{course}/modules', [AdminController::class, 'moduleStore'])->name('courses.modules.store');
        Route::delete('/modules/{module}', [AdminController::class, 'moduleDestroy'])->name('modules.destroy');
        Route::post('/modules/{module}/restore', [AdminController::class, 'moduleRestore'])->name('modules.restore');
        Route::post('/modules/{module}/lessons', [AdminController::class, 'lessonStore'])->name('modules.lessons.store');
        Route::delete('/lessons/{lesson}', [AdminController::class, 'lessonDestroy'])->name('lessons.destroy');
        Route::post('/lessons/{lesson}/restore', [AdminController::class, 'lessonRestore'])->name('lessons.restore');
        Route::post('/courses/{course}/faqs', [AdminController::class, 'courseFaqStore'])->name('courses.faqs.store');
        Route::delete('/course-faqs/{faq}', [AdminController::class, 'courseFaqDestroy'])->name('course-faqs.destroy');
        Route::get('/products', [AdminController::class, 'products'])->name('products');
        Route::get('/products/create', [AdminController::class, 'productCreate'])->name('products.create');
        Route::post('/products', [AdminController::class, 'productStore'])->name('products.store');
        Route::get('/products/{product}/edit', [AdminController::class, 'productEdit'])->name('products.edit');
        Route::put('/products/{product}', [AdminController::class, 'productUpdate'])->name('products.update');
        Route::delete('/products/{product}', [AdminController::class, 'productDestroy'])->name('products.destroy');
        Route::post('/products/{product}/restore', [AdminController::class, 'productRestore'])->name('products.restore');
        Route::post('/products/{product}/features', [AdminController::class, 'featureStore'])->name('products.features.store');
        Route::delete('/features/{feature}', [AdminController::class, 'featureDestroy'])->name('features.destroy');
        Route::post('/products/{product}/versions', [AdminController::class, 'versionStore'])->name('products.versions.store');
        Route::delete('/versions/{version}', [AdminController::class, 'versionDestroy'])->name('versions.destroy');
        Route::post('/products/{product}/faqs', [AdminController::class, 'productFaqStore'])->name('products.faqs.store');
        Route::delete('/faqs/{faq}', [AdminController::class, 'productFaqDestroy'])->name('faqs.destroy');
        Route::post('/products/{product}/images', [AdminController::class, 'productImageStore'])->name('products.images.store');
        Route::delete('/product-images/{image}', [AdminController::class, 'productImageDestroy'])->name('product-images.destroy');
        Route::get('/articles', [AdminController::class, 'articles'])->name('articles');
        Route::get('/articles/create', [AdminController::class, 'articleCreate'])->name('articles.create');
        Route::post('/articles', [AdminController::class, 'articleStore'])->name('articles.store');
        Route::get('/articles/{article}/edit', [AdminController::class, 'articleEdit'])->name('articles.edit');
        Route::put('/articles/{article}', [AdminController::class, 'articleUpdate'])->name('articles.update');
        Route::delete('/articles/{article}', [AdminController::class, 'articleDestroy'])->name('articles.destroy');
        Route::post('/articles/{article}/restore', [AdminController::class, 'articleRestore'])->name('articles.restore');
        Route::get('/messages', [AdminController::class, 'messages'])->name('messages');
        Route::patch('/messages/{message}', [AdminController::class, 'messageUpdate'])->name('messages.update');
        Route::post('/messages/{message}/read', [AdminController::class, 'messageRead'])->name('messages.read');
        Route::get('/topics', [AdminController::class, 'topics'])->name('topics');
        Route::get('/topics/create', [AdminController::class, 'topicCreate'])->name('topics.create');
        Route::post('/topics', [AdminController::class, 'topicStore'])->name('topics.store');
        Route::get('/topics/{topic}/edit', [AdminController::class, 'topicEdit'])->name('topics.edit');
        Route::put('/topics/{topic}', [AdminController::class, 'topicUpdate'])->name('topics.update');
        Route::get('/faqs', [AdminFaqController::class, 'index'])->name('faqs');
        Route::post('/faqs', [AdminFaqController::class, 'store'])->name('faqs.store');
        Route::put('/faqs/{source}/{id}', [AdminFaqController::class, 'update'])->whereNumber('id')->name('faqs.update');
        Route::delete('/faqs/{source}/{id}', [AdminFaqController::class, 'destroy'])->whereNumber('id')->name('faqs.manage.destroy');
        Route::get('/media', [MediaController::class, 'index'])->name('media');
        Route::post('/media', [MediaController::class, 'store'])->name('media.store');
        Route::put('/media/{media}', [MediaController::class, 'update'])->name('media.update');
        Route::delete('/media/{media}', [MediaController::class, 'destroy'])->name('media.destroy');
        Route::get('/settings', [SiteSettingsController::class, 'edit'])->name('settings');
        Route::put('/settings', [SiteSettingsController::class, 'update'])->name('settings.update');
        Route::get('/audit', [AdminAuditController::class, 'index'])->name('audit');
        Route::get('/search', [AdminSearchController::class, 'index'])->name('search');
        Route::get('/pages', [AdminPageController::class, 'index'])->name('pages');
        Route::get('/policies', [AdminPageController::class, 'policies'])->name('policies');
        Route::get('/pages/create', [AdminPageController::class, 'create'])->name('pages.create');
        Route::post('/pages', [AdminPageController::class, 'store'])->name('pages.store');
        Route::get('/pages/{page}/edit', [AdminPageController::class, 'edit'])->name('pages.edit');
        Route::put('/pages/{page}', [AdminPageController::class, 'update'])->name('pages.update');
        Route::get('/navigation', [AdminNavigationController::class, 'index'])->name('navigation');
        Route::post('/navigation', [AdminNavigationController::class, 'store'])->name('navigation.store');
        Route::put('/navigation/{navigationItem}', [AdminNavigationController::class, 'update'])->name('navigation.update');
        Route::delete('/navigation/{navigationItem}', [AdminNavigationController::class, 'destroy'])->name('navigation.destroy');
        Route::get('/categories', [AdminTaxonomyController::class, 'categories'])->name('categories');
        Route::post('/categories', [AdminTaxonomyController::class, 'categoryStore'])->name('categories.store');
        Route::delete('/categories/{category}', [AdminTaxonomyController::class, 'categoryDestroy'])->name('categories.destroy');
        Route::get('/tags', [AdminTaxonomyController::class, 'tags'])->name('tags');
        Route::post('/tags', [AdminTaxonomyController::class, 'tagStore'])->name('tags.store');
        Route::delete('/tags/{tag}', [AdminTaxonomyController::class, 'tagDestroy'])->name('tags.destroy');
        Route::get('/social-links', [AdminTaxonomyController::class, 'socialLinks'])->name('social-links');
        Route::post('/social-links', [AdminTaxonomyController::class, 'socialLinkStore'])->name('social-links.store');
        Route::put('/social-links/{socialLink}', [AdminTaxonomyController::class, 'socialLinkUpdate'])->name('social-links.update');
        Route::delete('/social-links/{socialLink}', [AdminTaxonomyController::class, 'socialLinkDestroy'])->name('social-links.destroy');
        Route::get('/commerce', [AdminCommerceController::class, 'dashboard'])->name('commerce.dashboard');
        Route::get('/commerce/orders', [AdminCommerceController::class, 'orders'])->name('commerce.orders');
        Route::get('/commerce/orders/{order}', [AdminCommerceController::class, 'order'])->name('commerce.orders.show');
        Route::post('/commerce/orders/{order}/refund', [AdminCommerceController::class, 'refund'])->name('commerce.orders.refund');
        Route::get('/commerce/payments', [AdminCommerceController::class, 'payments'])->name('commerce.payments');
        Route::get('/commerce/entitlements', [AdminCommerceController::class, 'entitlements'])->name('commerce.entitlements');
        Route::get('/commerce/enrollments', [AdminCommerceController::class, 'enrollments'])->name('commerce.enrollments');
        Route::get('/commerce/waitlists', [AdminCommerceController::class, 'waitlists'])->name('commerce.waitlists');
        Route::get('/commerce/waitlists/export', [AdminCommerceController::class, 'waitlistExport'])->name('commerce.waitlists.export');
        Route::post('/products/{product}/assets', [AdminCommerceController::class, 'assetStore'])->name('products.assets.store');
        Route::delete('/product-assets/{asset}', [AdminCommerceController::class, 'assetDestroy'])->name('product-assets.destroy');
    });
});
