@extends('layouts.admin')
@section('title', 'Site settings')
@section('content')
<div class="admin-heading"><div><p class="eyebrow">CMS / Settings</p><h1>Site settings</h1><p>One source of truth for public brand, contact, footer, SEO and disclosure content.</p></div></div>
<form class="admin-form" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('put')
<fieldset class="form-section"><legend>Brand and contact</legend><label>Brand name<input name="brand_name" value="{{ old('brand_name', $settings['brand_name']->value ?? '') }}" required></label><div class="form-row"><label>Contact email<input type="email" name="contact_email" value="{{ old('contact_email', $settings['contact_email']->value ?? '') }}" required></label><label>Phone<input name="contact_phone" value="{{ old('contact_phone', $settings['contact_phone']->value ?? '') }}"></label></div><div class="form-row"><label>WhatsApp<input name="contact_whatsapp" value="{{ old('contact_whatsapp', $settings['contact_whatsapp']->value ?? '') }}"></label><label>Location<input name="contact_location" value="{{ old('contact_location', $settings['contact_location']->value ?? '') }}"></label></div></fieldset>
<fieldset class="form-section"><legend>Brand media</legend>@include('admin.components.media-field', ['name' => 'logo', 'label' => 'Logo', 'value' => $settings['logo']->value ?? null, 'media' => $media])@include('admin.components.media-field', ['name' => 'dark_logo', 'label' => 'Dark logo', 'value' => $settings['dark_logo']->value ?? null, 'media' => $media])@include('admin.components.media-field', ['name' => 'favicon', 'label' => 'Favicon', 'value' => $settings['favicon']->value ?? null, 'media' => $media])@include('admin.components.media-field', ['name' => 'default_social_image', 'label' => 'Default social image', 'value' => $settings['default_social_image']->value ?? null, 'media' => $media])</fieldset>
<fieldset class="form-section"><legend>SEO and footer</legend><label>Default SEO title<input name="default_seo_title" value="{{ old('default_seo_title', $settings['default_seo_title']->value ?? '') }}" required></label><label>Default SEO description<textarea name="default_seo_description" rows="3" required>{{ old('default_seo_description', $settings['default_seo_description']->value ?? '') }}</textarea></label><label>Footer copy<textarea name="footer_copy" rows="3">{{ old('footer_copy', $settings['footer_copy']->value ?? '') }}</textarea></label><label>Risk disclaimer<textarea name="risk_disclaimer" rows="4" required>{{ old('risk_disclaimer', $settings['risk_disclaimer']->value ?? '') }}</textarea></label></fieldset>
<button class="button button-dark" type="submit">Save settings <span aria-hidden="true">↗</span></button></form>
@endsection
