@extends('layouts.admin')
@section('title', $member->exists ? 'Edit team member' : 'Add team member')
@section('portal-heading', 'Team')
@section('content')
<x-admin.page-header eyebrow="Platform / Team" title="{{ $member->exists ? 'Edit team member' : 'Add team member' }}" description="Publish only information that is accurate, approved and useful to a public visitor." />
<form class="admin-form admin-editor-form" method="post" action="{{ $action }}">@csrf @if($member->exists) @method('put') @endif
<x-admin.form-section title="Profile identity"><div class="form-row"><label>Full name<input name="name" value="{{ old('name', $member->name) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $member->slug) }}" required></label></div><div class="form-row"><label>Role / title <span>(optional)</span><input name="role" value="{{ old('role', $member->role) }}" placeholder="Only if confirmed"></label><label>Department / category <span>(optional)</span><input name="department" value="{{ old('department', $member->department) }}"></label></div><label>Short introduction <span>(optional)</span><textarea name="short_intro" rows="3">{{ old('short_intro', $member->short_intro) }}</textarea></label><label>Full bio <span>(optional)</span><textarea name="bio" rows="8">{{ old('bio', $member->bio) }}</textarea><small class="field-help">Rich text is sanitized before saving.</small></label><label>Focus <span>(optional)</span><textarea name="focus" rows="3">{{ old('focus', $member->focus) }}</textarea></label><label>Expertise / responsibilities <span>(one per line, optional)</span><textarea name="expertise" rows="5">{{ old('expertise', collect($member->expertise ?: [])->implode("\n")) }}</textarea></label></x-admin.form-section>
<x-admin.form-section title="Portrait"><x-admin.media-field name="portrait" label="Portrait" :value="$member->portrait" :media="$media" help="Use a clear, approved portrait. The public page crops this consistently across breakpoints." /><label>Focal point <span>(optional)</span><input name="portrait_focal_point" value="{{ old('portrait_focal_point', $member->portrait_focal_point ?: 'center 25%') }}" placeholder="e.g. center 25%"></label></x-admin.form-section>
<x-admin.form-section title="Public links"><p class="field-help">Only populated links render publicly. Leave fields empty rather than adding placeholders.</p><div class="form-row"><label>LinkedIn URL<input type="url" name="linkedin_url" value="{{ old('linkedin_url', $member->linkedin_url) }}"></label><label>Instagram URL<input type="url" name="instagram_url" value="{{ old('instagram_url', $member->instagram_url) }}"></label></div><div class="form-row"><label>X / Twitter URL<input type="url" name="x_url" value="{{ old('x_url', $member->x_url) }}"></label><label>Facebook URL<input type="url" name="facebook_url" value="{{ old('facebook_url', $member->facebook_url) }}"></label></div><div class="form-row"><label>YouTube URL<input type="url" name="youtube_url" value="{{ old('youtube_url', $member->youtube_url) }}"></label><label>TikTok URL<input type="url" name="tiktok_url" value="{{ old('tiktok_url', $member->tiktok_url) }}"></label></div><div class="form-row"><label>GitHub URL<input type="url" name="github_url" value="{{ old('github_url', $member->github_url) }}"></label><label>Website URL<input type="url" name="website_url" value="{{ old('website_url', $member->website_url) }}"></label></div><label>Public email <span>(optional)</span><input type="email" name="public_email" value="{{ old('public_email', $member->public_email) }}"></label></x-admin.form-section>
<x-admin.form-section title="Publishing"><div class="form-row"><label>Sort order<input type="number" min="0" name="sort_order" value="{{ old('sort_order', $member->sort_order) }}" required></label><x-admin.toggle name="is_featured" label="Featured on public surfaces" :checked="old('is_featured', $member->is_featured) == true" /><x-admin.toggle name="is_active" label="Active and visible" :checked="old('is_active', $member->is_active) == true" /></div></x-admin.form-section>
<x-admin.form-section title="SEO"><div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $member->seo_title) }}"></label><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $member->canonical_url) }}"></label></div><label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $member->seo_description) }}</textarea></label><div class="form-row"><label>Robots<select name="robots"><option value="index,follow" @selected(old('robots', $member->robots ?: 'index,follow') === 'index,follow')>Index, follow</option><option value="noindex,nofollow" @selected(old('robots', $member->robots) === 'noindex,nofollow')>No index</option></select></label><x-admin.media-field name="og_image" label="Open Graph image" :value="$member->og_image" :media="$media" /></div></x-admin.form-section>
<div class="admin-form-actions"><button class="button button-primary" type="submit">Save team member <span aria-hidden="true">↗</span></button><a class="button button-secondary" href="{{ route('admin.team') }}">Cancel</a></div>
</form>
@endsection
