@extends('layouts.public')
@php($heroImage = $project->featured_image ? \App\Support\PublicHero::candidate($project->featured_image) : null)
@section('title', $project->seo_title ?: $project->title.' — Mwanafunzi Investor')
@section('description', $project->seo_description ?: $project->short_description)
@section('canonical', $project->canonical_url ?: route('projects.show', $project))
@section('og_title', $project->og_title ?: $project->seo_title ?: $project->title)
@section('og_description', $project->og_description ?: $project->seo_description ?: $project->short_description)
@if($heroImage) @section('og_image', $heroImage['url']) @endif
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'CreativeWork', 'name' => $project->title, 'description' => $project->short_description, 'url' => route('projects.show', $project), 'image' => $heroImage['url'] ?? null, 'dateCreated' => $project->project_date?->toDateString()], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
    <x-public-hero class="public-page-hero project-detail-hero" :eyebrow="$project->project_type ?: 'Case study'" :title="$project->title" :summary="$project->short_description" :image="$project->featured_image" :overlay="'strong'" setting="hero_tools_image" :fallback-image="config('public.hero_defaults.modules')"><div class="project-meta-row">@if($project->industry)<span><small>Industry</small>{{ $project->industry }}</span>@endif @if($project->platform)<span><small>Platform</small>{{ $project->platform }}</span>@endif @if($project->timeline)<span><small>Timeline</small>{{ $project->timeline }}</span>@endif</div></x-public-hero>
    <section class="platform-section"><div class="container project-detail-layout"><article class="project-case-study">@if($project->full_introduction)<div class="project-intro rich-copy">{!! \App\Support\RichText::render($project->full_introduction) !!}</div>@endif @foreach([['challenge', 'The challenge'], ['role', 'My role'], ['approach', 'The approach'], ['solution', 'The solution']] as [$field, $heading]) @if($project->{$field})<section><p class="eyebrow"><span class="eyebrow-line"></span> {{ $heading }}</p><div class="rich-copy">{!! \App\Support\RichText::render($project->{$field}) !!}</div></section>@endif @endforeach @if($project->features)<section><p class="eyebrow"><span class="eyebrow-line"></span> Key features</p><div class="project-feature-list">@foreach($project->features as $feature)<div><h3>{{ $feature['title'] ?? '' }}</h3><p>{{ $feature['description'] ?? '' }}</p></div>@endforeach</div></section>@endif @if($project->results)<section><p class="eyebrow"><span class="eyebrow-line"></span> Result / impact</p><div class="project-results">@foreach($project->results as $result)<div><strong>{{ $result['value'] ?? '' }}</strong><span>{{ $result['label'] ?? '' }}</span>@if(!empty($result['description']))<p>{{ $result['description'] }}</p>@endif</div>@endforeach</div></section>@endif</article><aside class="project-detail-aside"><div><span>Role</span><strong>{{ $project->role ? 'Defined in case study' : 'Project delivery' }}</strong></div>@if($project->services->isNotEmpty())<div><span>Services</span><strong>{{ $project->services->pluck('title')->join(', ') }}</strong></div>@endif @if($project->technologies)<div><span>Technology</span><div class="portfolio-tags">@foreach($project->technologies as $technology)<small>{{ $technology }}</small>@endforeach</div></div>@endif @if($project->live_url)<a class="text-link" href="{{ $project->live_url }}" target="_blank" rel="noopener">Visit project <span aria-hidden="true">↗</span></a>@endif</aside></div></section>
    @if($project->gallery->isNotEmpty())<section class="platform-section platform-muted project-gallery-section"><div class="container"><p class="eyebrow"><span class="eyebrow-line"></span> Project gallery</p><div class="project-gallery">@foreach($project->gallery as $media)<figure><img src="{{ $media->url }}" @if($media->variants) srcset="{{ collect($media->variants)->map(fn($variant) => asset('storage/'.$variant['path']).' '.$variant['width'].'w')->implode(', ') }}" sizes="(max-width: 760px) 100vw, 50vw" @endif width="{{ $media->width ?: '' }}" height="{{ $media->height ?: '' }}" alt="{{ $media->pivot->alt_text ?: $media->alt_text ?: $project->title }}" loading="lazy">@if($media->pivot->caption)<figcaption>{{ $media->pivot->caption }}</figcaption>@endif</figure>@endforeach</div></div></section>@endif
    @if($project->testimonials->isNotEmpty())<section class="platform-section project-testimonials"><div class="container narrow-copy"><p class="eyebrow"><span class="eyebrow-line"></span> Client perspective</p>@foreach($project->testimonials as $testimonial)<blockquote>“{{ $testimonial->testimonial }}”<footer><strong>{{ $testimonial->displayName() }}</strong>@if($testimonial->client_role), {{ $testimonial->client_role }}@endif @unless($testimonial->hide_company && !$testimonial->anonymous_display) · {{ $testimonial->company }}@endunless</footer></blockquote>@endforeach</div></section>@endif
    @if($relatedProjects->isNotEmpty())<section class="platform-section"><div class="container"><div class="split-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> Keep exploring</p><h2>Related projects.</h2></div></div><div class="portfolio-project-grid">@foreach($relatedProjects as $related)<a class="portfolio-project-card" href="{{ route('projects.show', $related) }}">@if($related->featured_image)<img src="{{ \App\Support\PublicHero::candidate($related->featured_image)['url'] ?? asset(config('public.hero_defaults.default')) }}" alt="{{ $related->title }}" loading="lazy">@endif<div><span>{{ $related->project_type ?: 'Case study' }}</span><h3>{{ $related->title }}</h3><p>{{ $related->short_description }}</p></div></a>@endforeach</div></div></section>@endif
@endsection
