@extends('layouts.admin')
@section('title', $isCreate ? 'New learning topic' : 'Edit learning topic')
@section('portal-heading', 'Learning topics')
@section('content')
<x-admin.page-header eyebrow="CMS / Learn" title="{{ $isCreate ? 'New learning topic' : 'Edit learning topic' }}" description="Publish structured learning paths with controlled content, media, outcomes and course relationships." />
<a class="admin-back-link" href="{{ route('admin.topics') }}">← Back to topics</a>
<div class="admin-form-card"><form class="admin-form admin-editor-form" method="post" action="{{ $action }}" data-unsaved-warning>
    @csrf @if(!$isCreate) @method('put') @endif
    <label>Title<input name="title" value="{{ old('title', $topic->title) }}" required></label>
    <label>Slug<input name="slug" value="{{ old('slug', $topic->slug) }}" placeholder="Generated from title if blank"></label>
    @include('admin.components.media-field', ['name' => 'image', 'label' => 'Topic image', 'value' => $topic->image, 'media' => $media])
    <fieldset class="form-section"><legend>Hero and SEO</legend><div class="form-row"><label>Hero eyebrow<input name="hero_eyebrow" value="{{ old('hero_eyebrow', $topic->hero_eyebrow) }}"></label><label>Hero title<input name="hero_title" value="{{ old('hero_title', $topic->hero_title) }}" placeholder="Defaults to topic title"></label></div><label>Hero summary<textarea name="hero_summary" rows="3">{{ old('hero_summary', $topic->hero_summary) }}</textarea></label>@include('admin.components.media-field', ['name' => 'hero_image', 'label' => 'Hero image', 'value' => $topic->hero_image, 'media' => $media])<label>Hero image focal point<select name="hero_focal_point">@foreach(\App\Support\HeroFocalPoint::options() as $focalPoint)<option value="{{ $focalPoint }}" @selected(old('hero_focal_point', $topic->hero_focal_point ?: \App\Support\HeroFocalPoint::DEFAULT) === $focalPoint)>{{ str_replace(' ', ' · ', ucfirst($focalPoint)) }}</option>@endforeach</select></label><div class="form-row"><label>Hero overlay<select name="hero_overlay"><option value="light" @selected(old('hero_overlay', $topic->hero_overlay ?: 'medium') === 'light')>Light</option><option value="medium" @selected(old('hero_overlay', $topic->hero_overlay ?: 'medium') === 'medium')>Medium</option><option value="strong" @selected(old('hero_overlay', $topic->hero_overlay ?: 'medium') === 'strong')>Strong</option></select></label><label>Hero alignment<select name="hero_alignment"><option value="left" @selected(old('hero_alignment', $topic->hero_alignment ?: 'left') === 'left')>Left</option><option value="center" @selected(old('hero_alignment', $topic->hero_alignment ?: 'left') === 'center')>Center</option><option value="right" @selected(old('hero_alignment', $topic->hero_alignment ?: 'left') === 'right')>Right</option></select></label></div><div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $topic->seo_title) }}"></label>@include('admin.components.media-field', ['name' => 'og_image', 'label' => 'OpenGraph image', 'value' => $topic->og_image, 'media' => $media])</div><label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $topic->seo_description) }}</textarea></label><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $topic->canonical_url) }}"></label><div class="form-row"><label>Robots directive<select name="robots"><option value="">Index and follow (default)</option><option value="index,follow" @selected(old('robots', $topic->robots) === 'index,follow')>Index, follow</option><option value="noindex,nofollow" @selected(old('robots', $topic->robots) === 'noindex,nofollow')>Noindex, nofollow</option></select></label><label>OpenGraph title<input name="og_title" value="{{ old('og_title', $topic->og_title) }}"></label></div><label>OpenGraph description<textarea name="og_description" rows="2">{{ old('og_description', $topic->og_description) }}</textarea></label></fieldset>
    <div class="form-row"><label>Skill level<input name="skill_level" value="{{ old('skill_level', $topic->skill_level) }}"></label><label>Study time<input name="study_time" value="{{ old('study_time', $topic->study_time) }}"></label></div>
    <label>Expected availability <span>(optional, no invented dates)</span><input name="expected_availability" value="{{ old('expected_availability', $topic->expected_availability) }}"></label>
    <label>Short description<textarea name="short_description" rows="3" required>{{ old('short_description', $topic->short_description) }}</textarea></label>
    @include('admin.components.rich-text-field', ['name' => 'full_description', 'label' => 'Full description', 'value' => old('full_description', $topic->full_description)])
    <label>Learning outcomes <span>(one per line)</span><textarea name="learning_outcomes" rows="5">{{ old('learning_outcomes', collect($topic->learning_outcomes ?? [])->implode("\n")) }}</textarea></label>
    <fieldset class="form-section"><legend>Related courses</legend><div class="checkbox-grid">@foreach($courses as $course)<label class="checkbox-field"><input type="checkbox" name="course_ids[]" value="{{ $course->id }}" @checked(in_array($course->id, old('course_ids', $topic->courses?->pluck('id')->all() ?? [])))> <span>{{ $course->title }}</span></label>@endforeach</div></fieldset>
    <fieldset class="form-section"><legend>Related journal notes</legend><div class="checkbox-grid">@foreach($articles as $article)<label class="checkbox-field"><input type="checkbox" name="article_ids[]" value="{{ $article->id }}" @checked(in_array($article->id, old('article_ids', $topic->articles?->pluck('id')->all() ?? [])))> <span>{{ $article->title }}</span></label>@endforeach</div></fieldset>
    <fieldset class="form-section"><legend>Related tools</legend><div class="checkbox-grid">@foreach($products as $product)<label class="checkbox-field"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked(in_array($product->id, old('product_ids', $topic->products?->pluck('id')->all() ?? [])))> <span>{{ $product->name }}</span></label>@endforeach</div></fieldset>
    <label>Sort order<input type="number" name="sort_order" min="0" value="{{ old('sort_order', $topic->sort_order) }}" required></label>
    <label class="consent"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $topic->is_published))> <span>Published on the public site</span></label>
    <div class="form-actions"><button class="button button-dark" type="submit">{{ $isCreate ? 'Create topic' : 'Save topic' }} <span aria-hidden="true">↗</span></button>@if(!$isCreate)<a class="button button-light" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('admin.preview', now()->addMinutes(30), ['type' => 'topic', 'id' => $topic->id]) }}" target="_blank" rel="noopener">Preview</a><a class="button button-light" href="{{ route('learn.show', $topic) }}" target="_blank" rel="noopener">View public page</a>@endif</div>
</form></div>
@endsection
