@extends('layouts.admin')
@section('title', $article->exists ? 'Edit article' : 'New article')
@section('content')
<x-admin.page-header eyebrow="CMS / Journal" title="{{ $article->exists ? 'Edit article' : 'New article' }}" description="Shape the journal entry, media, publishing state and SEO metadata." />
<a class="admin-back-link" href="{{ route('admin.articles') }}">← Back to articles</a>
<div class="admin-form-card"><form class="admin-form admin-editor-form" method="post" action="{{ $action }}" data-unsaved-warning>@csrf @if($article->exists) @method('put') @endif
    <label>Title<input name="title" value="{{ old('title', $article->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $article->slug) }}"></label>
    <div class="form-row"><label>Category<select name="article_category_id"><option value="">Uncategorised</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('article_category_id', $article->article_category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Author<input name="author" value="{{ old('author', $article->author) }}"></label></div>
    @include('admin.components.media-field', ['name' => 'featured_image', 'label' => 'Featured image', 'value' => $article->featured_image, 'media' => $media])
    <label>Hero image focal point<select name="hero_focal_point">@foreach(\App\Support\HeroFocalPoint::options() as $focalPoint)<option value="{{ $focalPoint }}" @selected(old('hero_focal_point', $article->hero_focal_point ?: \App\Support\HeroFocalPoint::DEFAULT) === $focalPoint)>{{ str_replace(' ', ' · ', ucfirst($focalPoint)) }}</option>@endforeach</select></label>
    <label>Tags <span>(comma-separated)</span><input name="tags" value="{{ old('tags', $article->exists ? $article->tags->pluck('name')->implode(', ') : '') }}" placeholder="risk, process, probability"></label>
    <div class="form-row"><label>Status<select name="status"><option value="draft">Draft</option><option value="scheduled" @selected(old('status', $article->status) === 'scheduled')>Scheduled</option><option value="published" @selected(old('status', $article->status) === 'published')>Published</option><option value="archived" @selected(old('status', $article->status) === 'archived')>Archived</option></select></label><label>Published at<input type="datetime-local" name="published_at" value="{{ old('published_at', $article->published_at?->format('Y-m-d\\TH:i')) }}"><small>Future times remain private until they are due.</small></label></div>
    <div class="form-row"><label>Reading time (minutes)<input type="number" min="1" max="240" name="reading_time" value="{{ old('reading_time', $article->reading_time) }}"></label>@include('admin.components.media-field', ['name' => 'og_image', 'label' => 'OpenGraph image', 'value' => $article->og_image, 'media' => $media])</div>
    <label>Excerpt<textarea name="excerpt" rows="3">{{ old('excerpt', $article->excerpt) }}</textarea></label>@include('admin.components.rich-text-field', ['name' => 'content', 'label' => 'Content', 'value' => old('content', $article->content), 'help' => 'Use headings, emphasis, lists, links and quotes. The published output is sanitized.'])<label>SEO title<input name="seo_title" value="{{ old('seo_title', $article->seo_title) }}"></label><label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $article->seo_description) }}</textarea></label><div class="form-row"><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $article->canonical_url) }}"></label><label>Robots directive<select name="robots"><option value="">Index and follow (default)</option><option value="index,follow" @selected(old('robots', $article->robots) === 'index,follow')>Index, follow</option><option value="noindex,nofollow" @selected(old('robots', $article->robots) === 'noindex,nofollow')>Noindex, follow</option><option value="noindex,nofollow" @selected(old('robots', $article->robots) === 'noindex,nofollow')>Noindex, nofollow</option></select></label></div><div class="form-row"><label>OpenGraph title<input name="og_title" value="{{ old('og_title', $article->og_title) }}"></label><label>OpenGraph description<textarea name="og_description" rows="2">{{ old('og_description', $article->og_description) }}</textarea></label></div>
    <label class="consent"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $article->is_featured))> <span>Featured article</span></label><div class="form-actions"><button class="button button-dark" type="submit">Save article <span aria-hidden="true">↗</span></button>@if($article->exists)<a class="button button-light" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('admin.preview', now()->addMinutes(30), ['type' => 'article', 'id' => $article->id]) }}" target="_blank" rel="noopener">Preview</a>@endif</div>
</form></div>
@endsection
