@extends('layouts.admin')
@php($existingSocialLinks = old('social_links', $article->exists ? $article->socialLinks->map(fn ($link) => ['platform' => $link->platform, 'url' => $link->url, 'label' => $link->label])->values()->all() : []))
@php($editorTitle = !empty($dailyUpdate) ? 'New daily update' : ($article->exists ? 'Edit article' : 'New article'))
@section('title', $editorTitle)
@section('portal-heading', 'Journal')
@section('content')
<x-admin.page-header eyebrow="CMS / Journal" title="{{ $editorTitle }}" description="Shape the journal entry, attach social context, choose an author and control publication safely." />
<a class="admin-back-link" href="{{ route('admin.articles') }}">← Back to articles</a>
<div class="admin-form-card"><form class="admin-form admin-editor-form" method="post" action="{{ $action }}" data-unsaved-warning>@csrf @if($article->exists) @method('put') @endif
    <div class="admin-form-section-heading"><span class="eyebrow">Content</span><h2>What are we publishing?</h2></div>
    <label>Title<input name="title" value="{{ old('title', $article->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $article->slug) }}"><small>Use lowercase words separated by hyphens. Leave blank to generate it from the title.</small></label>
    <div class="form-row"><label>Content type<select name="content_type">@foreach($contentTypes as $value => $label)<option value="{{ $value }}" @selected(old('content_type', $article->content_type ?: 'article') === $value)>{{ $label }}</option>@endforeach</select></label><label>Category<select name="article_category_id"><option value="">Uncategorised</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('article_category_id', $article->article_category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label></div>
    <div class="form-row"><label>Author profile<select name="team_member_id"><option value="">Mwanafunzi Investor</option>@foreach($teamMembers as $member)<option value="{{ $member->id }}" @selected((string) old('team_member_id', $article->team_member_id) === (string) $member->id)>{{ $member->name }} — {{ $member->role }}</option>@endforeach</select></label><label>Legacy author label<input name="author" value="{{ old('author', $article->author) }}"><small>Used only when no team member profile is selected.</small></label></div>
    @include('admin.components.media-field', ['name' => 'featured_image', 'label' => 'Featured image', 'value' => $article->featured_image, 'media' => $media])
    <label>Hero image focal point<select name="hero_focal_point">@foreach(\App\Support\HeroFocalPoint::options() as $focalPoint)<option value="{{ $focalPoint }}" @selected(old('hero_focal_point', $article->hero_focal_point ?: \App\Support\HeroFocalPoint::DEFAULT) === $focalPoint)>{{ str_replace(' ', ' · ', ucfirst($focalPoint)) }}</option>@endforeach</select></label>
    <label>Tags <span>(comma-separated)</span><input name="tags" value="{{ old('tags', $article->exists ? $article->tags->pluck('name')->implode(', ') : '') }}" placeholder="risk, process, probability"></label>
    <label>Related learning topics<select name="learning_topic_ids[]" multiple size="4">@foreach($learningTopics as $topic)<option value="{{ $topic->id }}" @selected(in_array((string) $topic->id, array_map('strval', old('learning_topic_ids', $article->exists ? $article->learningTopics->pluck('id')->all() : [])), true))>{{ $topic->title }}</option>@endforeach</select><small>Attach the learning context that should connect this article to courses and tools.</small></label>
    <label>Excerpt<textarea name="excerpt" rows="3">{{ old('excerpt', $article->excerpt) }}</textarea></label>@include('admin.components.rich-text-field', ['name' => 'content', 'label' => 'Content', 'value' => old('content', $article->content), 'help' => 'Use headings, emphasis, lists, links and quotes. The published output is sanitized.'])

    <div class="admin-form-section-heading"><span class="eyebrow">Social context</span><h2>Link the wider conversation.</h2><p>Use real, public post URLs. Links are shown as safe cards on the article.</p></div>
    <div class="article-social-repeater" data-social-repeater>@forelse($existingSocialLinks as $index => $social)<div class="article-social-row" data-social-row><label>Platform<select name="social_links[{{ $index }}][platform]"><option value="instagram" @selected(($social['platform'] ?? '') === 'instagram')>Instagram</option><option value="facebook" @selected(($social['platform'] ?? '') === 'facebook')>Facebook</option><option value="tiktok" @selected(($social['platform'] ?? '') === 'tiktok')>TikTok</option><option value="youtube" @selected(($social['platform'] ?? '') === 'youtube')>YouTube</option><option value="x" @selected(($social['platform'] ?? '') === 'x')>X</option><option value="linkedin" @selected(($social['platform'] ?? '') === 'linkedin')>LinkedIn</option></select></label><label>Post URL<input type="url" name="social_links[{{ $index }}][url]" value="{{ $social['url'] ?? '' }}" placeholder="https://..."></label><label>Label<input name="social_links[{{ $index }}][label]" value="{{ $social['label'] ?? '' }}" placeholder="Watch the original update"></label><button class="button button-ghost button-small" type="button" data-remove-social>Remove</button></div>@empty<div class="article-social-row" data-social-row><label>Platform<select name="social_links[0][platform]"><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="x">X</option><option value="linkedin">LinkedIn</option></select></label><label>Post URL<input type="url" name="social_links[0][url]" placeholder="https://..."></label><label>Label<input name="social_links[0][label]" placeholder="Watch the original update"></label><button class="button button-ghost button-small" type="button" data-remove-social>Remove</button></div>@endforelse</div><button class="button button-secondary button-small" type="button" data-add-social>Add social post</button>

    <div class="admin-form-section-heading"><span class="eyebrow">Publishing</span><h2>Decide when it belongs in the public Journal.</h2></div>
    <div class="form-row"><label>Status<select name="status"><option value="draft" @selected(old('status', $article->status) === 'draft')>Draft</option><option value="scheduled" @selected(old('status', $article->status) === 'scheduled')>Scheduled</option><option value="published" @selected(old('status', $article->status) === 'published')>Published</option><option value="archived" @selected(old('status', $article->status) === 'archived')>Archived</option></select></label><label>Published at / schedule<input type="datetime-local" name="published_at" value="{{ old('published_at', $article->published_at?->format('Y-m-d\\TH:i')) }}"><small>Scheduled entries become visible automatically when this time arrives.</small></label></div>
    <div class="form-row"><label>Reading time (minutes)<input type="number" min="1" max="240" name="reading_time" value="{{ old('reading_time', $article->reading_time) }}"></label><label>Feature priority<input type="number" min="0" max="999" name="feature_priority" value="{{ old('feature_priority', $article->feature_priority ?: 0) }}"><small>Higher numbers appear first among featured entries.</small></label></div>
    <div class="form-row"><label>Feature starts<input type="datetime-local" name="feature_start_at" value="{{ old('feature_start_at', $article->feature_start_at?->format('Y-m-d\\TH:i')) }}"></label><label>Feature ends<input type="datetime-local" name="feature_end_at" value="{{ old('feature_end_at', $article->feature_end_at?->format('Y-m-d\\TH:i')) }}"></label></div>
    <label class="consent"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $article->is_featured))> <span>Feature this article on the Journal home</span></label>

    <div class="admin-form-section-heading"><span class="eyebrow">Search appearance</span><h2>Make the note easy to find.</h2></div>
    <div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $article->seo_title) }}"></label><label>SEO description<textarea name="seo_description" rows="2">{{ old('seo_description', $article->seo_description) }}</textarea></label></div><div class="form-row"><label>Canonical URL<input type="url" name="canonical_url" value="{{ old('canonical_url', $article->canonical_url) }}"></label><label>Robots directive<select name="robots"><option value="">Index and follow (default)</option><option value="index,follow" @selected(old('robots', $article->robots) === 'index,follow')>Index, follow</option><option value="noindex,follow" @selected(old('robots', $article->robots) === 'noindex,follow')>Noindex, follow</option><option value="noindex,nofollow" @selected(old('robots', $article->robots) === 'noindex,nofollow')>Noindex, nofollow</option></select></label></div><div class="form-row"><label>OpenGraph title<input name="og_title" value="{{ old('og_title', $article->og_title) }}"></label><label>OpenGraph description<textarea name="og_description" rows="2">{{ old('og_description', $article->og_description) }}</textarea></label></div>@include('admin.components.media-field', ['name' => 'og_image', 'label' => 'OpenGraph image', 'value' => $article->og_image, 'media' => $media])
    <div class="form-actions"><button class="button button-dark" type="submit">Save article <span aria-hidden="true">↗</span></button>@if($article->exists)<a class="button button-light" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('admin.preview', now()->addMinutes(30), ['type' => 'article', 'id' => $article->id]) }}" target="_blank" rel="noopener">Preview</a>@endif</div>
</form></div>
<template data-social-template><div class="article-social-row" data-social-row><label>Platform<select name="social_links[__INDEX__][platform]"><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="x">X</option><option value="linkedin">LinkedIn</option></select></label><label>Post URL<input type="url" name="social_links[__INDEX__][url]" placeholder="https://..."></label><label>Label<input name="social_links[__INDEX__][label]" placeholder="Watch the original update"></label><button class="button button-ghost button-small" type="button" data-remove-social>Remove</button></div></template>
@endsection
