@extends('layouts.admin')
@section('title', $product->exists ? 'Edit product' : 'New product')
@section('content')
<div class="admin-heading"><div><p class="eyebrow">CMS / Tools</p><h1>{{ $product->exists ? 'Edit product' : 'New product' }}</h1></div><a class="back-link" href="{{ route('admin.products') }}">← Back to products</a></div>
<form class="admin-form" method="post" action="{{ $action }}">@csrf @if($product->exists) @method('put') @endif
    <label>Name<input name="name" value="{{ old('name', $product->name) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $product->slug) }}"></label>
    @include('admin.components.media-field', ['name' => 'thumbnail', 'label' => 'Thumbnail', 'value' => $product->thumbnail, 'media' => $media])
    <div class="form-row"><label>Product type<input name="product_type" value="{{ old('product_type', $product->product_type) }}"></label><label>Availability<select name="availability"><option value="draft">Draft</option><option value="available" @selected(old('availability', $product->availability) === 'available')>Available</option><option value="coming_soon" @selected(old('availability', $product->availability) === 'coming_soon')>Coming soon</option><option value="waitlist" @selected(old('availability', $product->availability) === 'waitlist')>Waitlist</option><option value="unavailable" @selected(old('availability', $product->availability) === 'unavailable')>Unavailable</option><option value="archived" @selected(old('availability', $product->availability) === 'archived')>Archived</option></select></label></div>
    <label>Short description<textarea name="short_description" rows="3" required>{{ old('short_description', $product->short_description) }}</textarea></label><label>Detailed description<textarea name="detailed_description" rows="8">{{ old('detailed_description', $product->detailed_description) }}</textarea></label><label>Version<input name="version" value="{{ old('version', $product->version) }}"></label>
    <div class="form-row"><label>Price<input type="number" step="0.01" min="0" name="price" value="{{ old('price', $product->price) }}"></label><label>Sale price<input type="number" step="0.01" min="0" name="sale_price" value="{{ old('sale_price', $product->sale_price) }}"></label></div>
    <div class="form-row"><label>Currency<input name="currency" maxlength="3" value="{{ old('currency', $product->currency ?: 'USD') }}"></label><label>Download format<input name="download_format" value="{{ old('download_format', $product->download_format) }}"></label></div>
    <label>System requirements<textarea name="system_requirements" rows="3">{{ old('system_requirements', $product->system_requirements) }}</textarea></label>
    <div class="form-row"><label>Demo URL<input type="url" name="demo_url" value="{{ old('demo_url', $product->demo_url) }}"></label><label>Purchase URL<input type="url" name="purchase_url" value="{{ old('purchase_url', $product->purchase_url) }}"></label></div>
    <label>Documentation URL<input type="url" name="documentation_url" value="{{ old('documentation_url', $product->documentation_url) }}"></label>
    <div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $product->seo_title) }}"></label>@include('admin.components.media-field', ['name' => 'og_image', 'label' => 'OpenGraph image', 'value' => $product->og_image, 'media' => $media])</div>
    <label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $product->seo_description) }}</textarea></label>
    <label class="consent"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $product->is_featured))> <span>Featured product</span></label><div class="form-actions"><button class="button button-dark" type="submit">Save product <span aria-hidden="true">↗</span></button>@if($product->exists)<a class="button button-light" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('admin.preview', now()->addMinutes(30), ['type' => 'product', 'id' => $product->id]) }}" target="_blank" rel="noopener">Preview</a>@endif</div>
</form>
@if($product->exists)
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Product architecture</p><h2>FAQs</h2></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.products.faqs.store', $product) }}">@csrf<div class="form-row"><label>Question<input name="question" required></label><label>Sort order<input type="number" name="sort_order" value="0" min="0" required></label></div><label>Answer<textarea name="answer" rows="3" required></textarea></label><button class="button button-dark" type="submit">Add FAQ <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@foreach($product->faqs as $faq)<div class="admin-subresource-header"><div><strong>{{ $faq->question }}</strong><small>{{ $faq->answer }}</small></div><form method="post" action="{{ route('admin.faqs.destroy', $faq) }}">@csrf @method('delete')<button type="submit">Remove</button></form></div>@endforeach</div>
</section>
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Product architecture</p><h2>Features and versions</h2></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.products.features.store', $product) }}">@csrf<div class="form-row"><label>Feature title<input name="title" required></label><label>Sort order<input type="number" name="sort_order" value="0" min="0" required></label></div><label>Description<textarea name="description" rows="2"></textarea></label><button class="button button-dark" type="submit">Add feature <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@foreach($product->features as $feature)<div class="admin-subresource-header"><div><strong>{{ $feature->title }}</strong><small>{{ $feature->description }}</small></div><form method="post" action="{{ route('admin.features.destroy', $feature) }}">@csrf @method('delete')<button type="submit">Remove</button></form></div>@endforeach</div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.products.versions.store', $product) }}">@csrf<div class="form-row"><label>Version<input name="version" required></label><label>Released at<input type="date" name="released_at"></label></div><label>Notes<textarea name="notes" rows="3"></textarea></label><button class="button button-dark" type="submit">Add version <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@foreach($product->versions as $version)<div class="admin-subresource-header"><div><strong>{{ $version->version }}</strong><small>{{ $version->released_at?->format('M j, Y') }} @if($version->notes) · {{ $version->notes }} @endif</small></div><form method="post" action="{{ route('admin.versions.destroy', $version) }}">@csrf @method('delete')<button type="submit">Remove</button></form></div>@endforeach</div>
</section>
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Product media</p><h2>Screenshots</h2></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.products.images.store', $product) }}" enctype="multipart/form-data">@csrf
        @include('admin.components.media-field', ['name' => 'existing_path', 'label' => 'Select existing screenshot', 'value' => null, 'media' => $media, 'help' => 'Or upload a new screenshot below.'])
        <div class="form-row"><label>Upload new screenshot<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,image/svg+xml"></label><label>Alt text<input name="alt_text" required placeholder="Describe what the screenshot shows"></label></div><button class="button button-dark" type="submit">Add screenshot <span aria-hidden="true">+</span></button></form>
    <div class="media-grid">@foreach($product->images as $image)<article class="media-card"><img src="{{ asset('storage/'.$image->path) }}" alt="{{ $image->alt_text }}"><small>{{ $image->alt_text }}</small><form method="post" action="{{ route('admin.product-images.destroy', $image) }}">@csrf @method('delete')<button type="submit">Remove</button></form></article>@endforeach</div>
</section>
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Private delivery</p><h2>Downloadable assets</h2><p>Files are stored on the private disk and are only served through entitlement checks.</p></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.products.assets.store', $product) }}" enctype="multipart/form-data">@csrf<div class="form-row"><label>File<input type="file" name="file" accept=".xlsx,.xlsm,.pdf,.zip,.csv" required></label><label>Name <span>(optional)</span><input name="name"></label></div><div class="form-row"><label>Version <span>(optional)</span><select name="product_version_id"><option value="">No version</option>@foreach($product->versions as $version)<option value="{{ $version->id }}">{{ $version->version }}</option>@endforeach</select></label><label>Delivery policy<select name="download_policy"><option value="current_and_future">Purchased version + future releases</option><option value="purchased_version">Purchased version only</option></select></label></div><button class="button button-dark" type="submit">Upload protected asset <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@forelse($product->assets as $asset)<div class="admin-subresource-header"><div><strong>{{ $asset->name }}</strong><small>{{ strtoupper($asset->extension) }} · {{ number_format($asset->size / 1048576, 2) }} MB · {{ $asset->download_policy }}</small></div><form method="post" action="{{ route('admin.product-assets.destroy', $asset) }}">@csrf @method('delete')<button type="submit">Remove</button></form></div>@empty<div class="empty-state compact"><p>No protected assets uploaded yet.</p></div>@endforelse</div>
</section>
@endif
@endsection
