@extends('layouts.admin')
@section('title', $testimonial->exists ? 'Edit testimonial' : 'Add testimonial')
@section('portal-heading', 'Testimonials')
@section('content')
<x-admin.page-header eyebrow="Portfolio / Social proof" title="{{ $testimonial->exists ? 'Edit testimonial' : 'Add testimonial' }}" description="Do not add invented quotes, ratings, organizations or outcomes. Use privacy controls when the client should not be fully identified." />
<form class="admin-form admin-editor-form" method="post" action="{{ $action }}">@csrf @if($testimonial->exists) @method('put') @endif
<x-admin.form-section title="Client perspective"><div class="form-row"><label>Client name<input name="client_name" value="{{ old('client_name', $testimonial->client_name) }}" required></label><label>Role / title<input name="client_role" value="{{ old('client_role', $testimonial->client_role) }}"></label></div><label>Company<input name="company" value="{{ old('company', $testimonial->company) }}"></label><label>Testimonial<textarea name="testimonial" rows="7" required>{{ old('testimonial', $testimonial->testimonial) }}</textarea></label><div class="form-row"><x-admin.media-field name="client_photo" label="Client photo" :value="$testimonial->client_photo" :media="$media" /><x-admin.media-field name="company_logo" label="Company logo" :value="$testimonial->company_logo" :media="$media" /></div></x-admin.form-section>
<x-admin.form-section title="Attribution and privacy"><div class="form-row"><label>Related project<select name="project_id"><option value="">No project linked</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int) old('project_id', $testimonial->project_id) === $project->id)>{{ $project->title }}</option>@endforeach</select></label><label>Source URL <span>(optional)</span><input type="url" name="source_url" value="{{ old('source_url', $testimonial->source_url) }}"></label></div><div class="admin-check-grid"><x-admin.toggle name="anonymous_display" label="Display as anonymous client" :checked="old('anonymous_display', $testimonial->anonymous_display) == true" /><x-admin.toggle name="initials_only" label="Display initials only" :checked="old('initials_only', $testimonial->initials_only) == true" /><x-admin.toggle name="hide_company" label="Hide company" :checked="old('hide_company', $testimonial->hide_company) == true" /></div></x-admin.form-section>
<x-admin.form-section title="Publishing"><div class="form-row"><label>Rating <span>(optional)</span><input type="number" name="rating" min="1" max="5" value="{{ old('rating', $testimonial->rating) }}"></label><label>Date<input type="date" name="testimonial_date" value="{{ old('testimonial_date', $testimonial->testimonial_date?->format('Y-m-d')) }}"></label></div><div class="form-row"><label>Display order<input type="number" name="sort_order" min="0" value="{{ old('sort_order', $testimonial->sort_order) }}" required></label><x-admin.toggle name="is_featured" label="Feature on homepage" :checked="old('is_featured', $testimonial->is_featured) == true" /><x-admin.toggle name="is_published" label="Publish testimonial" :checked="old('is_published', $testimonial->is_published) == true" /></div></x-admin.form-section>
<div class="admin-form-actions"><button class="button button-primary" type="submit">Save testimonial <span aria-hidden="true">↗</span></button><a class="button button-secondary" href="{{ route('admin.testimonials') }}">Cancel</a></div>
</form>
@endsection
