@extends('layouts.account')
@section('title', 'Profile — Mwanafunzi Investor')
@section('portal-heading', 'Profile')
@section('content')
<section class="student-page-heading"><div><p class="student-eyebrow">Account / Profile</p><h1>Your profile.</h1><p>Manage your personal information and how your account appears in the workspace.</p></div></section>
<div class="student-account-layout">
    <aside class="student-profile-summary"><div class="student-profile-avatar-wrap"><x-portal-avatar :user="$user" size="large" /></div><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p><x-portal-status :status="$user->hasVerifiedEmail() ? 'verified' : 'pending'" :label="$user->hasVerifiedEmail() ? 'Verified email' : 'Verification required'" /><dl class="student-definition-list"><div><dt>Member since</dt><dd>{{ $user->created_at?->format('M j, Y') ?: 'Not recorded' }}</dd></div><div><dt>Account status</dt><dd>{{ str($user->status ?: 'active')->title() }}</dd></div></dl><form method="post" action="{{ route('account.profile.avatar.update') }}" enctype="multipart/form-data" class="student-avatar-form" data-avatar-form>@csrf<label class="student-button student-button-secondary" for="customer-avatar">Choose photo</label><input id="customer-avatar" type="file" name="avatar" accept="image/jpeg,image/png,image/webp,image/avif" hidden required data-avatar-input><button class="student-text-button" type="submit">Upload cropped photo</button><small data-avatar-crop-status>JPG, PNG, WebP or AVIF up to 4 MB.</small></form>@if($user->avatar_path)<form method="post" action="{{ route('account.profile.avatar.remove') }}">@csrf @method('delete')<button class="student-text-button" type="submit">Remove photo</button></form>@endif</aside>
    <div class="student-profile-sections">
        <x-portal-card class="student-panel"><div class="student-panel-heading"><div><p class="student-eyebrow">Personal information</p><h2>Keep your details current.</h2></div></div><form class="student-form" method="post" action="{{ route('account.profile.update') }}">@csrf @method('put')<div class="student-form-grid"><label>Full name<input name="name" value="{{ old('name', $user->name) }}" autocomplete="name" required></label><label>Email address <span class="student-label-note">managed securely</span><input value="{{ $user->email }}" readonly autocomplete="email"><small>Email changes require a separate verification flow.</small></label><label>Phone number<input name="phone" value="{{ old('phone', $user->phone) }}" autocomplete="tel" placeholder="e.g. +255 787 172 686"></label><label>Country / region<input name="country" maxlength="2" value="{{ old('country', $user->country) }}" autocomplete="country" placeholder="TZ"><small>Use a two-letter country code.</small></label></div><div class="student-form-actions"><button class="student-button student-button-dark" type="submit">Save changes <span aria-hidden="true">↗</span></button></div></form></x-portal-card>
        <x-portal-card class="student-panel student-panel-soft"><div class="student-panel-heading"><div><p class="student-eyebrow">Account information</p><h2>At a glance</h2></div></div><dl class="student-definition-list student-definition-list-wide"><div><dt>Email verification</dt><dd><x-portal-status :status="$user->hasVerifiedEmail() ? 'verified' : 'pending'" :label="$user->hasVerifiedEmail() ? 'Verified' : 'Pending'" /></dd></div><div><dt>Customer since</dt><dd>{{ $user->created_at?->format('F Y') ?: 'Not recorded' }}</dd></div><div><dt>Email address</dt><dd class="student-breakable">{{ $user->email }}</dd></div></dl>@unless($user->hasVerifiedEmail())<a class="student-button student-button-secondary" href="{{ route('verification.notice') }}">Verify email <span aria-hidden="true">↗</span></a>@endunless</x-portal-card>
    </div>
</div>
<div class="admin-avatar-crop-modal" data-avatar-crop-modal hidden role="dialog" aria-modal="true" aria-labelledby="customer-avatar-crop-title"><div class="admin-avatar-crop-card"><div class="admin-avatar-crop-header"><div><p class="student-eyebrow">Profile photo</p><h2 id="customer-avatar-crop-title">Crop your picture</h2></div><button class="admin-avatar-crop-close" type="button" aria-label="Close crop dialog" data-avatar-crop-cancel>×</button></div><p class="admin-avatar-crop-help">Drag the image to position it, then adjust the zoom.</p><div class="admin-avatar-crop-canvas-wrap"><canvas width="360" height="360" data-avatar-crop-canvas></canvas></div><label class="admin-avatar-zoom">Zoom<input type="range" min="1" max="3" step="0.01" value="1" data-avatar-crop-zoom></label><div class="admin-confirm-actions"><button class="student-button student-button-secondary" type="button" data-avatar-crop-cancel>Cancel</button><button class="student-button student-button-primary" type="button" data-avatar-crop-apply>Use cropped photo</button></div></div></div>
@endsection
