@extends('layouts.admin')
@section('title', $course->exists ? 'Edit course' : 'New course')
@section('content')
<div class="admin-heading"><div><p class="eyebrow">CMS / Courses</p><h1>{{ $course->exists ? 'Edit course' : 'New course' }}</h1></div><a class="back-link" href="{{ route('admin.courses') }}">← Back to courses</a></div>
<form class="admin-form" method="post" action="{{ $action }}">@csrf @if($course->exists) @method('put') @endif
    <label>Title<input name="title" value="{{ old('title', $course->title) }}" required></label>
    <label>Slug<input name="slug" value="{{ old('slug', $course->slug) }}" placeholder="Generated from title if blank"></label>
    @include('admin.components.media-field', ['name' => 'featured_image', 'label' => 'Featured image', 'value' => $course->featured_image, 'media' => $media])
    <div class="form-row"><label>Level<input name="level" value="{{ old('level', $course->level) }}"></label><label>Duration<input name="duration" value="{{ old('duration', $course->duration) }}"></label></div><label>Expected availability <span>(optional for coming-soon courses; do not invent dates)</span><input name="expected_availability" value="{{ old('expected_availability', $course->expected_availability) }}"></label>
    <div class="form-row"><label>Price<input type="number" step="0.01" min="0" name="price" value="{{ old('price', $course->price) }}"></label><label>Currency<input name="currency" maxlength="3" value="{{ old('currency', $course->currency ?: 'USD') }}"></label></div>
    <label>Instructor<input name="instructor" value="{{ old('instructor', $course->instructor) }}"></label>
    <div class="form-row"><label>Status<select name="status"><option value="draft">Draft</option><option value="published" @selected(old('status', $course->status) === 'published')>Published</option><option value="open" @selected(old('status', $course->status) === 'open')>Open for enrollment</option><option value="closed" @selected(old('status', $course->status) === 'closed')>Closed</option><option value="coming_soon" @selected(old('status', $course->status) === 'coming_soon')>Coming soon</option><option value="archived" @selected(old('status', $course->status) === 'archived')>Archived</option></select></label><label>CTA label<input name="cta_label" value="{{ old('cta_label', $course->cta_label) }}"></label></div>
    <label>Short description<textarea name="short_description" rows="3" required>{{ old('short_description', $course->short_description) }}</textarea></label>
    <label>Full description<textarea name="full_description" rows="8">{{ old('full_description', $course->full_description) }}</textarea></label>
    <div class="form-row"><label>SEO title<input name="seo_title" value="{{ old('seo_title', $course->seo_title) }}"></label>@include('admin.components.media-field', ['name' => 'og_image', 'label' => 'OpenGraph image', 'value' => $course->og_image, 'media' => $media])</div>
    <label>SEO description<textarea name="seo_description" rows="3">{{ old('seo_description', $course->seo_description) }}</textarea></label>
    <label class="consent"><input type="checkbox" name="enrollment_available" value="1" @checked(old('enrollment_available', $course->enrollment_available))> <span>Enrollment available</span></label>
    <label class="consent"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $course->is_featured))> <span>Featured course</span></label>
    <div class="form-actions"><button class="button button-dark" type="submit">Save course <span aria-hidden="true">↗</span></button>@if($course->exists)<a class="button button-light" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('admin.preview', now()->addMinutes(30), ['type' => 'course', 'id' => $course->id]) }}" target="_blank" rel="noopener">Preview</a>@endif</div>
</form>
@if($course->exists)
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Course architecture</p><h2>FAQs</h2></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.courses.faqs.store', $course) }}">@csrf<div class="form-row"><label>Question<input name="question" required></label><label>Sort order<input type="number" name="sort_order" value="0" min="0" required></label></div><label>Answer<textarea name="answer" rows="3" required></textarea></label><button class="button button-dark" type="submit">Add FAQ <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@foreach($course->faqs as $faq)<div class="admin-subresource-header"><div><strong>{{ $faq->question }}</strong><small>{{ $faq->answer }}</small></div><form method="post" action="{{ route('admin.course-faqs.destroy', $faq) }}">@csrf @method('delete')<button type="submit">Remove</button></form></div>@endforeach</div>
</section>
<section class="admin-subresource"><div class="admin-heading"><div><p class="eyebrow">Course architecture</p><h2>Modules and lessons</h2></div></div>
    <form class="admin-form admin-inline-form" method="post" action="{{ route('admin.courses.modules.store', $course) }}">@csrf<div class="form-row"><label>Module title<input name="title" required></label><label>Sort order<input type="number" name="sort_order" value="0" min="0" required></label></div><label>Description<textarea name="description" rows="2"></textarea></label><button class="button button-dark" type="submit">Add module <span aria-hidden="true">+</span></button></form>
    <div class="admin-subresource-list">@forelse($course->modules as $module)<article class="admin-subresource-item {{ $module->trashed() ? 'is-archived' : '' }}"><div class="admin-subresource-header"><div><strong>{{ $module->title }}</strong>@if($module->trashed()) <em class="status-badge">Archived</em>@endif<small>{{ $module->description }}</small></div>@if($module->trashed())<form method="post" action="{{ route('admin.modules.restore', $module->id) }}">@csrf<button type="submit">Restore module</button></form>@else<form method="post" action="{{ route('admin.modules.destroy', $module) }}">@csrf @method('delete')<button type="submit">Remove module</button></form>@endif</div><div class="lesson-admin-list">@foreach($module->lessons as $lesson)<div class="{{ $lesson->trashed() ? 'is-archived' : '' }}"><span>{{ $lesson->title }} @if($lesson->trashed())<em class="status-badge">Archived</em>@endif</span>@if($lesson->trashed())<form method="post" action="{{ route('admin.lessons.restore', $lesson->id) }}">@csrf<button type="submit">Restore</button></form>@else<form method="post" action="{{ route('admin.lessons.destroy', $lesson) }}">@csrf @method('delete')<button type="submit">Remove</button></form>@endif</div>@endforeach</div>@if(! $module->trashed())<form class="admin-form admin-inline-form" method="post" action="{{ route('admin.modules.lessons.store', $module) }}">@csrf<div class="form-row"><label>Lesson title<input name="title" required></label><label>Sort order<input type="number" name="sort_order" value="0" min="0" required></label></div><label>Lesson content<textarea name="content" rows="3"></textarea></label><label class="consent"><input type="checkbox" name="is_published" value="1"> <span>Published</span></label><button class="button button-small button-light" type="submit">Add lesson <span aria-hidden="true">+</span></button></form>@endif</article>@empty<div class="empty-state compact"><p>No modules yet.</p></div>@endforelse</div>
</section>
@endif
@endsection
