@extends('layouts.public')
@php($ogImage = $product->og_image ? \App\Support\PublicHero::candidate($product->og_image) : null)
@section('title', ($product->seo_title ?: $product->name) . ' — Mwanafunzi Investor')
@section('description', $product->seo_description ?: $product->short_description)
@section('canonical', $product->canonical_url ?: route('tools.show', $product))
@section('robots', $product->robots ?: 'index,follow')
@section('og_title', $product->og_title ?: ($product->seo_title ?: $product->name))
@section('og_description', $product->og_description ?: ($product->seo_description ?: $product->short_description))
@if($ogImage) @section('og_image', $ogImage['url']) @endif
@section('structured_data')<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Product', 'name' => $product->name, 'description' => $product->short_description, 'url' => route('tools.show', $product), 'image' => $ogImage['url'] ?? null, 'brand' => ['@type' => 'Brand', 'name' => \App\Models\SiteSetting::getValue('brand_name', 'Mwanafunzi Investor')]], JSON_UNESCAPED_SLASHES) !!}</script>@endsection
@section('content')
<x-public-hero class="detail-hero" compact :eyebrow="$product->product_type ?: 'Digital tool'" :title="$product->name" :summary="$product->short_description" :image="$product->thumbnail" setting="hero_tools_image" :fallback-image="config('public.hero_defaults.tools')" :metadata="[$product->availability]" :breadcrumbs="[['label' => 'All tools', 'url' => route('tools')]]"><div class="detail-actions"><span class="status-badge">{{ str_replace('_', ' ', $product->availability) }}</span>@if($product->isPurchasable())<a class="button button-accent" href="{{ auth()->check() && auth()->user()->hasVerifiedEmail() ? route('checkout.product', $product) : route('login') }}">{{ $product->effectivePrice() === '0.00' ? 'Get free product' : 'Buy this tool' }} <span aria-hidden="true">↗</span></a>@else<a class="button button-light" href="{{ route('contact') }}">Ask about this tool <span aria-hidden="true">↗</span></a>@endif</div></x-public-hero>
<section class="platform-section"><div class="container two-column detail-grid"><div><p class="eyebrow">What it does</p><div class="rich-copy">{!! \App\Support\RichText::render($product->detailed_description ?: $product->short_description) !!}</div>@if($product->features->isNotEmpty())<h2>Features</h2><ul class="check-list">@foreach($product->features as $feature)<li><strong>{{ $feature->title }}</strong>@if($feature->description)<br>{{ $feature->description }}@endif</li>@endforeach</ul>@endif</div><aside class="detail-card"><span class="eyebrow">Product notes</span><dl><div><dt>Format</dt><dd>{{ $product->download_format ?: 'To be confirmed' }}</dd></div><div><dt>Version</dt><dd>{{ $product->version ?: 'In preparation' }}</dd></div><div><dt>Availability</dt><dd>{{ str_replace('_', ' ', $product->availability) }}</dd></div></dl><p>Product details and pricing will be published as each tool is ready.</p></aside></div></section>
<section class="platform-section platform-muted"><div class="container"><p class="eyebrow">Screenshots & versions</p><h2>Built for deliberate practice.</h2>@if($product->images->isNotEmpty())<div class="article-grid">@foreach($product->images as $image)<figure class="article-card"><img src="{{ asset('storage/'.$image->path) }}" alt="{{ $image->alt_text }}"><figcaption>{{ $image->alt_text }}</figcaption></figure>@endforeach</div>@endif @if($product->versions->isNotEmpty())<div class="module-list">@foreach($product->versions as $version)<details open><summary>{{ $version->version }} <span>{{ $version->released_at?->format('M Y') }}</span></summary><p>{{ $version->notes }}</p></details>@endforeach</div>@else<div class="empty-state compact"><p>Product screenshots, documentation and changelogs will appear here when the corresponding assets are ready. No unrelated stock photography is used.</p></div>@endif</div></section>
@if($product->faqs->isNotEmpty())<section class="platform-section"><div class="container"><p class="eyebrow">Questions</p><h2>Tool FAQs</h2><div class="module-list">@foreach($product->faqs as $faq)<details><summary>{{ $faq->question }} <span>+</span></summary><p>{{ $faq->answer }}</p></details>@endforeach</div></div></section>@endif
@endsection
